var trackRecordArray = new Array();

//Main Sections
trackRecordArray = [
{id:"3", thumb:"../../../images/trackRecord/logo_aon.png", largeImg:"../../../images/trackRecord/logo_aon_lrg.png", location:["hong kong"], branch:['<span class="bold">52,870 sqft</span> at Times Square, Hong Kong'], industry:"insurance", companyName:"AON",caseStudy:["../../case-studies/apac/hongkong-insurance.html"]},
{id:"7", thumb:"../../../images/trackRecord/logo_societe_generale.png", largeImg:"../../../images/trackRecord/logo_societe_generale_lrg.png", location:["beijing","hong kong","singapore"], branch:['<span class="bold">64,583 sqft</span> at TaiKang International Tower, Beijing','<span class="bold">110,00 sqft</span> at Pacific Place 3, Hong Kong','<span class="bold">46,015 sqft</span> at One Raffles Quay, Singapore'], industry:"banking", companyName:"Societe Generale",caseStudy:["../../case-studies/apac/beijing-banking.html","../../case-studies/apac/hongkong-banking.html",""]},
{id:"12", thumb:"../../../images/trackRecord/logo_ubs.png", largeImg:"../../../images/trackRecord/logo_ubs_lrg.png", location:["seoul","hong kong","singapore"], branch:['<span class="bold">64,729 sqft</span> at SFC, Seoul','<span class="bold">24,100 sqft</span> at Two International Finance Centre, Hong Kong','<span class="bold">229,000 sqft</span> at One Raffles Quay, Singapore'], industry:"banking", companyName:"UBS",caseStudy:["../../case-studies/apac/seoul-banking.html","",""]},
{id:"15", thumb:"../../../images/trackRecord/logo_kirkland_ellis.png", largeImg:"../../../images/trackRecord/logo_kirkland_ellis_lrg.png", location:['hong kong','shanghai'], branch:['<span class="bold">12,679 sqft; 5,451 sqft; 5,291 sqft</span> at Gloucester Tower, Hong Kong', '<span class="bold">7,535 sqft</span> at CITIC Square, Shanghai'], industry:"legal", companyName:"Kirkland & Ellis",caseStudy:["../../case-studies/apac/hongkong-legal.html",""]},
{id:"18", thumb:"../../../images/trackRecord/logo_herbert_smith.png", largeImg:"../../../images/trackRecord/logo_herbert_smith_lrg.png", location:['beijing','hong kong','bangkok'], branch:['<span class="bold">13,455 sqft</span> at Yintai, Beijing ','<span class="bold">30,555 sqft</span> at Gloucester Tower, Hong Kong','<span class="bold">8,180 sqft</span> at Abdulrahim Place, Bangkok'], industry:"legal", companyName:"Herbert Smith Freehills",caseStudy:["../../case-studies/apac/beijing-legal.html","",""]},
{id:"21", thumb:"../../../images/trackRecord/logo_paul_hastings.png", largeImg:"../../../images/trackRecord/logo_paul_hastings_lrg.png", location:["tokyo"], branch:['<span class="bold">13,035 sqft</span> at Sengokuyama MORI Tower, Tokyo'], industry:"legal", companyName:"Paul Hastings",caseStudy:["../../case-studies/apac/tokyo-legal.html"]},
{id:"22", thumb:"../../../images/trackRecord/logo_withers.png", largeImg:"../../../images/trackRecord/logo_withers_lrg.png", location:["singapore"], branch:['<span class="bold">1,970 sqft</span> at OUB Plaza 1, Singapore'], industry:"legal", companyName:"Withers",caseStudy:["../../case-studies/apac/singapore-legal.html"]},
{id:"27", thumb:"../../../images/trackRecord/logo_pwc.png", largeImg:"../../../images/trackRecord/logo_pwc_lrg.png", location:['shanghai','hong kong'], branch:['<span class="bold">116,250 sqft</span> at DBS Bank Tower, Shanghai','<span class="bold">33,318 sqft</span> at Manulife Financial Center, Hong Kong'], industry:"others", companyName:"PriceWaterhouseCoopers",caseStudy:["../../case-studies/apac/shanghai-banking.html",""]},
{id:"38", thumb:"../../../images/trackRecord/logo_philip_morris.png", largeImg:"../../../images/trackRecord/logo_philip_morris_lrg.png", location:["seoul"], branch:['<span class="bold">63,392 sqft</span> at IFC Tower One, Seoul'], industry:"others", companyName:"Phillip Morris",caseStudy:["../../case-studies/apac/seoul-others.html"]},
{id:"60", thumb:"../../../images/trackRecord/logo_lockton.png", largeImg:"../../../images/trackRecord/logo_lockton_lrg.png", location:["singapore"], branch:['<span class="bold">8,000 sqft</span> at One Raffles Place, Tower 2, Singapore'], industry:"insurance", companyName:"Lockton",caseStudy:["../../case-studies/apac/singapore-insurance.html"]},
{id:"61", thumb:"../../../images/trackRecord/logo_commerzbank.png", largeImg:"../../../images/trackRecord/logo_commerzbank_lrg.png", location:["tokyo"], branch:['<span class="bold">13,315 sqft</span> at Atago Green Hills MORI Tower, Toyko'], industry:"banking", companyName:"Commerzbank",caseStudy:["../../case-studies/apac/tokyo-banking.html"]},
{id:"62", thumb:"../../../images/trackRecord/logo_brit_insurance.png", largeImg:"../../../images/trackRecord/logo_brit_insurance_lrg.png", location:["tokyo"], branch:['<span class="bold">1,959 sqft</span> at Fuerte Kojimachi, Toyko'], industry:"insurance", companyName:"Brit Insurance",caseStudy:["../../case-studies/apac/tokyo-insurance.html"]}
];