var ourTeamArray = new Array();

//Main Sections
ourTeamArray = [

{id:"0", empName:"Iain Chapman", empTitle:"Managing Director, Strategic Real Estate Services, Asia Pacific", empDepartment:"Regional Commercial Services", telNo:"+852 2842 4223", email:"ichapman@savills.com.hk", location:"Hong Kong, China", experience:"25", languages:"English", expertise:"Legal / Banking / Accounting", workCat:[
	{cat:'leadership', locale:'china'},
	{cat:'leadership', locale:'hong kong'},
	{cat:'leadership', locale:'macau'},
	{cat:'leadership', locale:'taiwan'},
	{cat:'leadership', locale:'japan'},
	{cat:'leadership', locale:'south korea'},
	{cat:'leadership', locale:'singapore'},
	{cat:'leadership', locale:'thailand'},
	{cat:'leadership', locale:'vietnam'},
	{cat:'leadership', locale:'myanmar'},
	{cat:'leadership', locale:'australia'},
	{cat:'leadership', locale:'new zealand'},
	{cat:'leadership', locale:'india'},
	{cat:'leadership', locale:'malaysia'},
	{cat:'leadership', locale:'philippines'},
	{cat:'leadership', locale:'indonesia'},
	{cat:'asia pacific account management', locale:'china'},
	{cat:'asia pacific account management', locale:'hong kong'},
	{cat:'asia pacific account management', locale:'macau'},
	{cat:'asia pacific account management', locale:'taiwan'},
	{cat:'asia pacific account management', locale:'japan'},
	{cat:'asia pacific account management', locale:'south korea'},
	{cat:'asia pacific account management', locale:'singapore'},
	{cat:'asia pacific account management', locale:'thailand'},
	{cat:'asia pacific account management', locale:'vietnam'},
	{cat:'asia pacific account management', locale:'myanmar'},
	{cat:'asia pacific account management', locale:'australia'},
	{cat:'asia pacific account management', locale:'new zealand'},
	{cat:'asia pacific account management', locale:'india'},
	{cat:'asia pacific account management', locale:'malaysia'},
	{cat:'asia pacific account management', locale:'philippines'},
	{cat:'asia pacific account management', locale:'indonesia'}]
},
{id:"1", empName:"John Mackenzie", empTitle:"Divisional Director", empDepartment:"Corporate Real Estate Services", telNo:"+61 (0) 2 8215 8982", email:"jmackenzie@savills.com.au", location:"Sydney & Melbourne, Australia", experience:"37", languages:"English", expertise:"All Sectors", workCat:[
	{cat:'tenant representation', locale:'australia'},
	{cat:'tenant representation', locale:'new zealand'}]},
{id:"2", empName:"Dominic Harding", empTitle:"Senior Account Manager, Strategic Real Estate Services, Asia Pacific", empDepartment:"Account Management", telNo:"+65 6415 1078 (Ext 3078)", email:"dharding@savills.com.sg", location:"Singapore", experience:"4", languages:"English", expertise:"Corporate Real Estate", workCat:[
	{cat:'asia pacific account management', locale:'china'},
	{cat:'asia pacific account management', locale:'hong kong'},
	{cat:'asia pacific account management', locale:'macau'},
	{cat:'asia pacific account management', locale:'taiwan'},
	{cat:'asia pacific account management', locale:'japan'},
	{cat:'asia pacific account management', locale:'south korea'},
	{cat:'asia pacific account management', locale:'singapore'},
	{cat:'asia pacific account management', locale:'thailand'},
	{cat:'asia pacific account management', locale:'vietnam'},
	{cat:'asia pacific account management', locale:'myanmar'},
	{cat:'asia pacific account management', locale:'australia'},
	{cat:'asia pacific account management', locale:'new zealand'},
	{cat:'asia pacific account management', locale:'india'},
	{cat:'asia pacific account management', locale:'malaysia'},
	{cat:'asia pacific account management', locale:'philippines'},
	{cat:'asia pacific account management', locale:'indonesia'}]},
{id:"3", empName:"James Sherrard", empTitle:"Senior Director", empDepartment:"Head of Project Management for Asia Pacific", telNo:"+852 2840 4720", email:"jsherrard@savills.asia", location:"Hong Kong", experience:"17", languages:"English & French", expertise:"Project Management & Commercial Management", workCat:[
	{cat:'leadership', locale:'china'},
	{cat:'leadership', locale:'hong kong'},
	{cat:'leadership', locale:'macau'},
	{cat:'leadership', locale:'taiwan'},
	{cat:'leadership', locale:'japan'},
	{cat:'leadership', locale:'south korea'},
	{cat:'leadership', locale:'singapore'},
	{cat:'leadership', locale:'thailand'},
	{cat:'leadership', locale:'vietnam'},
	{cat:'leadership', locale:'myanmar'},
	{cat:'leadership', locale:'australia'},
	{cat:'leadership', locale:'new zealand'},
	{cat:'leadership', locale:'india'},
	{cat:'leadership', locale:'malaysia'},
	{cat:'leadership', locale:'philippines'},
	{cat:'leadership', locale:'indonesia'},
	{cat:'asia pacific account management', locale:'china'},
	{cat:'asia pacific account management', locale:'hong kong'},
	{cat:'asia pacific account management', locale:'macau'},
	{cat:'asia pacific account management', locale:'taiwan'},
	{cat:'asia pacific account management', locale:'japan'},
	{cat:'asia pacific account management', locale:'south korea'},
	{cat:'asia pacific account management', locale:'singapore'},
	{cat:'asia pacific account management', locale:'thailand'},
	{cat:'asia pacific account management', locale:'vietnam'},
	{cat:'asia pacific account management', locale:'myanmar'},
	{cat:'asia pacific account management', locale:'australia'},
	{cat:'asia pacific account management', locale:'new zealand'},
	{cat:'asia pacific account management', locale:'india'},
	{cat:'asia pacific account management', locale:'malaysia'},
	{cat:'asia pacific account management', locale:'philippines'},
	{cat:'asia pacific account management', locale:'indonesia'}]},
{id:"4", empName:"Ben Hopkins", empTitle:"Country Manager", empDepartment:"Project Management", telNo:"+65 6415 3657", email:"bhopkins@savills.com.sg", location:"Singapore", experience:"11", languages:"English & Portuguese", expertise:"Banking / Education / Oil & Gas / Legal / Industrial / Media", workCat:[
	{cat:'project management lead', locale:'singapore'},
	{cat:'project management lead', locale:'malaysia'},
	{cat:'project management lead', locale:'thailand'}
]},
{id:"5", empName:"Phill Andrew", empTitle:"Managing Director", empDepartment:"Project Management", telNo:"+61 (0) 2 82158922", email:"PAndrew@savills.com.au", location:"Sydney, Australia", experience:"25", languages:"English", expertise:"Management System & Fit-out", workCat:[
	{cat:'project management lead', locale:'australia'},
	{cat:'project management lead', locale:'new zealand'}]},
{id:"6", empName:"Julian Wyatt", empTitle:"Senior Director", empDepartment:"Facilities management", telNo:"+852 2534 1400 ", email:"jwyatt@savills.com.hk", location:"Hong Kong", experience:"Over 20", languages:"English", expertise:"Facilities management", workCat:[
	{cat:'intergrated facilities management', locale:'china'},
	{cat:'intergrated facilities management', locale:'hong kong'},
	{cat:'intergrated facilities management', locale:'macau'},
	{cat:'intergrated facilities management', locale:'taiwan'},
	{cat:'intergrated facilities management', locale:'japan'},
	{cat:'intergrated facilities management', locale:'south korea'},
	{cat:'intergrated facilities management', locale:'singapore'},
	{cat:'intergrated facilities management', locale:'thailand'},
	{cat:'intergrated facilities management', locale:'vietnam'},
	{cat:'intergrated facilities management', locale:'myanmar'},
	{cat:'intergrated facilities management', locale:'australia'},
	{cat:'intergrated facilities management', locale:'new zealand'},
	{cat:'intergrated facilities management', locale:'india'},
	{cat:'intergrated facilities management', locale:'malaysia'},
	{cat:'intergrated facilities management', locale:'philippines'},
	{cat:'intergrated facilities management', locale:'indonesia'}]},
{id:"7", empName:"Anthony Mcquade", empTitle:"Senior National Director", empDepartment:"", telNo:"+86 (10) 5925 2002", email:"anthony.mcquade@savills.com.cn", location:"Beijing, China", experience:"21", languages:"English, Mandarin", expertise:"All Sectors", workCat:[{cat:'intergrated facilities management', locale:'china'},
	{cat:'intergrated facilities management', locale:'hong kong'},
	{cat:'intergrated facilities management', locale:'macau'},
	{cat:'intergrated facilities management', locale:'taiwan'},
	{cat:'intergrated facilities management', locale:'japan'},
	{cat:'intergrated facilities management', locale:'south korea'},
	{cat:'intergrated facilities management', locale:'singapore'},
	{cat:'intergrated facilities management', locale:'thailand'},
	{cat:'intergrated facilities management', locale:'vietnam'},
	{cat:'intergrated facilities management', locale:'myanmar'},
	{cat:'intergrated facilities management', locale:'australia'},
	{cat:'intergrated facilities management', locale:'new zealand'},
	{cat:'intergrated facilities management', locale:'india'},
	{cat:'intergrated facilities management', locale:'malaysia'},
	{cat:'intergrated facilities management', locale:'philippines'},
	{cat:'intergrated facilities management', locale:'indonesia'}]},
{id:"8", empName:"Peter Wong", empTitle:"Senior Director", empDepartment:"Facilities management ", telNo:"+852 2534 1781", email:"pwong@savills.com.hk", location:"Hong Kong", experience:"36", languages:"Cantonese & English", expertise:"Building Services Engineering", workCat:[{cat:'intergrated facilities management', locale:'china'},
	{cat:'intergrated facilities management', locale:'hong kong'},
	{cat:'intergrated facilities management', locale:'macau'},
	{cat:'intergrated facilities management', locale:'taiwan'},
	{cat:'intergrated facilities management', locale:'japan'},
	{cat:'intergrated facilities management', locale:'south korea'},
	{cat:'intergrated facilities management', locale:'singapore'},
	{cat:'intergrated facilities management', locale:'thailand'},
	{cat:'intergrated facilities management', locale:'vietnam'},
	{cat:'intergrated facilities management', locale:'myanmar'},
	{cat:'intergrated facilities management', locale:'australia'},
	{cat:'intergrated facilities management', locale:'new zealand'},
	{cat:'intergrated facilities management', locale:'india'},
	{cat:'intergrated facilities management', locale:'malaysia'},
	{cat:'intergrated facilities management', locale:'philippines'},
	{cat:'intergrated facilities management', locale:'indonesia'}]},
{id:"9", empName:"James Chow", empTitle:"Director", empDepartment:"Project Consultancy", telNo:"+852 2534 1409", email:"jchow@savills.com.hk", location:"Hong Kong", experience:"Over 20", languages:"English, Cantonese, Mandarin", expertise:"Building Consultancy Projects", workCat:[
	{cat:'project management lead', locale:'hong kong'},
	{cat:'project management lead', locale:'macau'}]},
{id:"10", empName:"Chris Marriott", empTitle:"Chief Executive Officer", empDepartment:"South East Asia", telNo:"+65 6415 3888", email:"cjmarriott@savills.com", location:"Singapore", experience:"Over 20", languages:"English", expertise:"All Sectors", workCat:[{cat:'tenant representation', locale:'singapore'}]},
{id:"13", empName:"Ricky Lau", empTitle:"Senior Director", empDepartment:"Commercial Leasing", telNo:"+852 2842 4501", email:"rklau@savills.com.hk", location:"Hong Kong", experience:"17", languages:"English, Cantonese & Mandarin", expertise:"Tenant & Landlord Representation, Lease Renewal & Restructure", workCat:[{cat:'tenant representation', locale:'hong kong'}]},
{id:"14", empName:"Sue Lee", empTitle:"Director", empDepartment:"Commercial Leasing Services", telNo:"+82 (2) 2124 4180", email:"slee@savills.com.kr", location:"Seoul, South Korea", experience:"12", languages:"Korean & English", expertise:"Legal / Pharmaceutical / Korean conglomerate", workCat:[{cat:'tenant representation',locale:'south korea'}]},
{id:"15", empName:"Kevin Murtagh", empTitle:"Senior Manager", empDepartment:"Commercial", telNo:"+65 6415 7334", email:"kevin.murtagh@savills.com.sg", location:"Singapore", experience:"6", languages:"English, German, Indonesian", expertise:"All Sectors", workCat:[
	{cat:'tenant representation', locale:'singapore'},
	{cat:'tenant representation', locale:'indonesia'},
	{cat:'asia pacific account management', locale:'china'},
	{cat:'asia pacific account management', locale:'hong kong'},
	{cat:'asia pacific account management', locale:'macau'},
	{cat:'asia pacific account management', locale:'taiwan'},
	{cat:'asia pacific account management', locale:'japan'},
	{cat:'asia pacific account management', locale:'south korea'},
	{cat:'asia pacific account management', locale:'singapore'},
	{cat:'asia pacific account management', locale:'thailand'},
	{cat:'asia pacific account management', locale:'vietnam'},
	{cat:'asia pacific account management', locale:'myanmar'},
	{cat:'asia pacific account management', locale:'australia'},
	{cat:'asia pacific account management', locale:'new zealand'},
	{cat:'asia pacific account management', locale:'india'},
	{cat:'asia pacific account management', locale:'malaysia'},
	{cat:'asia pacific account management', locale:'philippines'},
	{cat:'asia pacific account management', locale:'indonesia'}]},
{id:"16", empName:"Jeffrey Wong", empTitle:"Deputy Senior Director", empDepartment:"Commercial Leasing", telNo:"+852 2842 4290", email:"jwong@savills.com.hk", location:"Hong Kong", experience:"10", languages:"English, Cantonese & Mandarin", expertise:"Tenant Representation & Rent Review", workCat:[{cat:'tenant representation', locale:'hong kong'}]},
{id:"17", empName:"Rupert Provest", empTitle:"Director", empDepartment:"Agency", telNo:"+84 8 3823 9205", email:"rprovest@savills.com.vn", location:"HCM City Vietnam", experience:"16", languages:"English", expertise:"Commercial", workCat:[
	{cat:'tenant representation', locale:'vietnam'},
	{cat:'project management lead', locale:'vietnam'},
	{cat:'project management lead', locale:'indonesia'}]},
{id:"18", empName:"Thanatchamon Wonglokniyom", empTitle:"Associate Director", empDepartment:"", telNo:"+66 (0) 2 636 0300", email:"thanatchamonw@savills.com.th", location:"Bangkok, Thailand", experience:"16", languages:"Thai & English", expertise:"Retail", workCat:[{cat:'tenant representation',locale:'thailand'}]},
{id:"20", empName:"Toshihide Honoki", empTitle:"Tenant Representation", empDepartment:"", telNo:"+81 (0) 3 5562 1721", email:"thonoki@savills.co.jp", location:"Tokyo, Japan", experience:"Over 10", languages:"English & Japanese", expertise:"Tenant Representation", workCat:[{cat:'tenant representation',locale:'japan'}]},
{id:"22", empName:"Doug Osborne", empTitle:"Managing Director", empDepartment:"", telNo:"+64 (0) 9951 5910", email:"dosborne@savills.co.nz", location:"New Zealand", experience:"40", languages:"English", expertise:"Strategic and Corporate Real Estate Advisory", workCat:[
	{cat:'tenant representation', locale:'new zealand'}]},
{id:"23", empName:"Michael Mccullough", empTitle:"Managing Director", empDepartment:"KMC MAG Group", telNo:"+63 2403 5519", email:"michael@kmcmaggroup.com", location:"Manila, Philippines", experience:"5", languages:"English & Filipino", expertise:"Tenant Representation / Customer Services Centres", workCat:[{cat:'tenant representation',locale:'philippines'}]},
/*{id:"24", empName:"Ricky Huang", empTitle:"Associate Director", empDepartment:"Investment ", telNo:"+8662 8789 5828", email:"rhuang@savills.com.tw", location:"Taiwan", experience:"9", languages:"English & Mandarin", expertise:"Industrial & Commercial", workCat:[{cat:'industrial', locale:'taiwan'}]},*/
{id:"26", empName:"Tony Chai", empTitle:"Senior Director", empDepartment:"Project Management", telNo:"+82 2 2124 4231", email:"shchai@savills.com.kr", location:"Seoul", experience:"25", languages:"English & Korean", expertise:"Development and Remodeling", workCat:[{cat:'project management lead', locale:'south korea'}]},
{id:"27", empName:"Adam Evennett", empTitle:"Associate Director", empDepartment:"", telNo:"+86 186 2167 2365", email:"adam.evennett@savills.com.cn", location:"Shanghai, China", experience:"10", languages:"English & intermediate Mandarin", expertise:"Building Refurbishment & Interiors for Retail and Commercial Fit Out", workCat:[
	{cat:'project management lead', locale:'china'},
	{cat:'project management lead', locale:'taiwan'},
	{cat:'project management lead', locale:'japan'}]},
{id:"29", empName:"Darren Curry", empTitle:"Divisional Director", empDepartment:"Industrial", telNo:"+61 (0) 29761 1304", email:"dcurry@savills.com.au", location:"Melbourne & Sydney, Australia", experience:"20", languages:"English", expertise:"Pre-lease Co-ordination / Sales and Leasing Projects / Industrial Investment / Project Marketing", workCat:[
	{cat:'industrial', locale:'china'},
	{cat:'industrial', locale:'hong kong'},
	{cat:'industrial', locale:'macau'},
	{cat:'industrial', locale:'taiwan'},
	{cat:'industrial', locale:'japan'},
	{cat:'industrial', locale:'south korea'},
	{cat:'industrial', locale:'singapore'},
	{cat:'industrial', locale:'thailand'},
	{cat:'industrial', locale:'vietnam'},
	{cat:'industrial', locale:'myanmar'},
	{cat:'industrial', locale:'australia'},
	{cat:'industrial', locale:'new zealand'},
	{cat:'industrial', locale:'india'},
	{cat:'industrial', locale:'malaysia'},
	{cat:'industrial', locale:'philippines'},
	{cat:'industrial', locale:'indonesia'}
	]},
{id:"30", empName:"James Siu", empTitle:"Senior Director", empDepartment:"Industrial and Kowloon Investment Sales", telNo:"+852 2378 8638", email:"jsiu@savills.com.hk", location:"Hong Kong", experience:"30", languages:"Putonghua & Cantonese", expertise:"Industrial / Logistics", workCat:[{cat:'industrial', locale:'china'},
	{cat:'industrial', locale:'hong kong'},
	{cat:'industrial', locale:'macau'},
	{cat:'industrial', locale:'taiwan'},
	{cat:'industrial', locale:'japan'},
	{cat:'industrial', locale:'south korea'},
	{cat:'industrial', locale:'singapore'},
	{cat:'industrial', locale:'thailand'},
	{cat:'industrial', locale:'vietnam'},
	{cat:'industrial', locale:'myanmar'},
	{cat:'industrial', locale:'australia'},
	{cat:'industrial', locale:'new zealand'},
	{cat:'industrial', locale:'india'},
	{cat:'industrial', locale:'malaysia'},
	{cat:'industrial', locale:'philippines'},
	{cat:'industrial', locale:'indonesia'}]},
{id:"31", empName:"Angela Lu", empTitle:"Manager", empDepartment:"Transaction Management", telNo:"+886 2 8789 5828", email:"Alu@savills.com.tw", location:"Taiwan", experience:"8", languages:"English & Chinese", expertise:"Commercial and Corporate Real Estate", workCat:[{cat:'tenant representation', locale:'taiwan'}]},
{id:"32", empName:"Ben Vickery", empTitle:"Regional Co-ordinator (Korea)", empDepartment:"Transaction Management & Industrial", telNo:"+82 2 2124 4172 ", email:"bvickery@savills.co.kr", location:"Seoul, South Korea", experience:"3", languages:"English", expertise:"Tenant Rep. Legal, Banking & tech", workCat:[{cat:'industrial', locale:'china'},
	{cat:'industrial', locale:'hong kong'},
	{cat:'industrial', locale:'macau'},
	{cat:'industrial', locale:'taiwan'},
	{cat:'industrial', locale:'japan'},
	{cat:'industrial', locale:'south korea'},
	{cat:'industrial', locale:'singapore'},
	{cat:'industrial', locale:'thailand'},
	{cat:'industrial', locale:'vietnam'},
	{cat:'industrial', locale:'myanmar'},
	{cat:'industrial', locale:'australia'},
	{cat:'industrial', locale:'new zealand'},
	{cat:'industrial', locale:'india'},
	{cat:'industrial', locale:'malaysia'},
	{cat:'industrial', locale:'philippines'},
	{cat:'industrial', locale:'indonesia'}]},
{id:"33", empName:"Dale O'Toole", empTitle:"National Sustainability Manager", empDepartment:"Sustainability", telNo:"+61 (0) 3 8686 8037 ", email:"dotoole@savills.com.au", location:"Australia", experience:"Over 20", languages:"English", expertise:"Sustainability ", workCat:[
	{cat:'sustainability', locale:'china'},
	{cat:'sustainability', locale:'hong kong'},
	{cat:'sustainability', locale:'macau'},
	{cat:'sustainability', locale:'taiwan'},
	{cat:'sustainability', locale:'japan'},
	{cat:'sustainability', locale:'south korea'},
	{cat:'sustainability', locale:'singapore'},
	{cat:'sustainability', locale:'thailand'},
	{cat:'sustainability', locale:'vietnam'},
	{cat:'sustainability', locale:'myanmar'},
	{cat:'sustainability', locale:'australia'},
	{cat:'sustainability', locale:'new zealand'},
	{cat:'sustainability', locale:'india'},
	{cat:'sustainability', locale:'malaysia'},
	{cat:'sustainability', locale:'philippines'},
	{cat:'sustainability', locale:'indonesia'}]},
{id:"34", empName:"Alexander Ang", empTitle:"Marketing Executive", empDepartment:"Transaction Management", telNo:"+6010 366 7087", email:"alexang@savillsrahim-co.com", location:"Kuala Lumpur, Malaysia", experience:"2", languages:"English, Mandarin, Cantonese & Malay", expertise:"Relocation, Tenant-Rep", workCat:[
{cat:'tenant representation', locale:'malaysia'}
]},
{id:"35", empName:"Daniel Byrne", empTitle:"Development Manager", empDepartment:"Transaction Management", telNo:"+64 (0) 9 951 5913", email:"dbyrne@savills.com.nz", location:"New Zealand", experience:"11", languages:"English", expertise:"Corporate Commercial Real Estate and Investment Sales", workCat:[
	{cat:'tenant representation',locale:'new zealand'}]},
{id:"36", empName:"Jerry Yan", empTitle:"Associate Director", empDepartment:"Transaction Management", telNo:"+8610 5925 2288", email:"jerry.yan@savills.com.cn", location:"Beijing, China", experience:"7", languages:"English & Chinese (Mandarin) ", expertise:"Commercial Real Estate. Tier 1 and Tier 2 Chinese cities",
workCat:[
	{cat:'tenant representation', locale:'china'},
	{cat:'tenant representation', locale:'japan'},
	{cat:'tenant representation', locale:'south korea'},
	{cat:'tenant representation', locale:'india'}
	]},
{id:"37", empName:"Terence Lau", empTitle:"Director ", empDepartment:"Transaction Management", telNo:"+0755 8828 5703", email:"terence.lau@savills.com.cn", location:"Shenzhen, China", experience:"Over 20", languages:"English, Mandarin & Cantonese", expertise:"All areas of commercial real estate", workCat:[{cat:'tenant representation',locale:'china'}]},
{id:"38", empName:"Nick Bradstreet", empTitle:"Deputy Managing Director & Head of Leasing", empDepartment:"Retail", telNo:"+852 2842 4255", email:"nbradstreet@savills.com.hk", location:"Hong Kong", experience:"27", languages:"English", expertise:"Retail / Shopping Centers. Regional leasing requirements", workCat:[
	{cat:'retail', locale:'china'},
	{cat:'retail', locale:'hong kong'},
	{cat:'retail', locale:'macau'},
	{cat:'retail', locale:'taiwan'},
	{cat:'retail', locale:'japan'},
	{cat:'retail', locale:'south korea'},
	{cat:'retail', locale:'singapore'},
	{cat:'retail', locale:'thailand'},
	{cat:'retail', locale:'vietnam'},
	{cat:'retail', locale:'myanmar'},
	{cat:'retail', locale:'australia'},
	{cat:'retail', locale:'new zealand'},
	{cat:'retail', locale:'india'},
	{cat:'retail', locale:'malaysia'},
	{cat:'retail', locale:'philippines'},
	{cat:'retail', locale:'indonesia'}
	]},
{id:"39", empName:"Lucas Shen", empTitle:"Manager", empDepartment:"Account Management", telNo:"+852 2842 4247", email:"Lshen@savills.com.hk", location:"Hong Kong", experience:"3", languages:"English and Cantonese", expertise:"Commercial Real Estate", workCat:[{cat:'tenant representation', locale:'hong kong'}]},
{id:"40", empName:"John Kim", empTitle:"Senior Manager", empDepartment:"Industrial", telNo:"+82 2 2124 4257", email:"dokim@savills.co.kr", location:"Seoul, South Korea", experience:"7", languages:"Korean & English", expertise:"Manufacturing/Automotive/Pharmaceutical", workCat:[{cat:'tenant representation', locale:'south korea'}]},
{id:"41", empName:"Dominic Peters", empTitle:"Director", empDepartment:"Industrial", telNo:"+65 64515 3638", email:"dpeters@savills.com.sg", location:"Singapore", experience:"20", languages:"English", expertise:"Industrial", workCat:[
	{cat:'industrial', locale:'china'},
	{cat:'industrial', locale:'hong kong'},
	{cat:'industrial', locale:'macau'},
	{cat:'industrial', locale:'taiwan'},
	{cat:'industrial', locale:'japan'},
	{cat:'industrial', locale:'south korea'},
	{cat:'industrial', locale:'singapore'},
	{cat:'industrial', locale:'thailand'},
	{cat:'industrial', locale:'vietnam'},
	{cat:'industrial', locale:'myanmar'},
	{cat:'industrial', locale:'australia'},
	{cat:'industrial', locale:'new zealand'},
	{cat:'industrial', locale:'india'},
	{cat:'industrial', locale:'malaysia'},
	{cat:'industrial', locale:'philippines'},
	{cat:'industrial', locale:'indonesia'}]},
{id:"44", empName:"Chris Adam", empTitle:"General Manager", empDepartment:"Project Management - VIC", telNo:"+61 (0) 3 9445 6841", email:"cadam@savills.com.au", location:"Melbourne, Australia", experience:"10", languages:"English", expertise:"Commercial development, refurbishment and fitout, data centres", workCat:[
	{cat:'project management lead', locale:'australia'},
	{cat:'project management lead', locale:'new zealand'}]},
{id:"45", empName:"Doris Lam", empTitle:"Account Manager, Business Development Strategic Real Estate Services", empDepartment:"", telNo:"+852 2842 4410", email:"dslam@savills.com.hk", location:"Hong Kong", experience:"8", languages:"English & Cantonese", expertise:"Corporate Real Estate", workCat:[{cat:'asia pacific account management', locale:'china'},
	{cat:'asia pacific account management', locale:'hong kong'},
	{cat:'asia pacific account management', locale:'macau'},
	{cat:'asia pacific account management', locale:'taiwan'},
	{cat:'asia pacific account management', locale:'japan'},
	{cat:'asia pacific account management', locale:'south korea'},
	{cat:'asia pacific account management', locale:'singapore'},
	{cat:'asia pacific account management', locale:'thailand'},
	{cat:'asia pacific account management', locale:'vietnam'},
	{cat:'asia pacific account management', locale:'myanmar'},
	{cat:'asia pacific account management', locale:'australia'},
	{cat:'asia pacific account management', locale:'new zealand'},
	{cat:'asia pacific account management', locale:'india'},
	{cat:'asia pacific account management', locale:'malaysia'},
	{cat:'asia pacific account management', locale:'philippines'},
	{cat:'asia pacific account management', locale:'indonesia'}]},
{id:"47", empName:"Nicky Wightman", empTitle:"Business Strategy Consultant", empDepartment:"", telNo:"+44(0) 1223 347 087", email:"nwightman@savills.com", location:"UK", experience:"6", languages:"English & French", expertise:"Corporate Strategy & Innovation", workCat:[
	{cat:'sustainability', locale:'china'},
	{cat:'sustainability', locale:'hong kong'},
	{cat:'sustainability', locale:'macau'},
	{cat:'sustainability', locale:'taiwan'},
	{cat:'sustainability', locale:'japan'},
	{cat:'sustainability', locale:'south korea'},
	{cat:'sustainability', locale:'singapore'},
	{cat:'sustainability', locale:'thailand'},
	{cat:'sustainability', locale:'vietnam'},
	{cat:'sustainability', locale:'myanmar'},
	{cat:'sustainability', locale:'australia'},
	{cat:'sustainability', locale:'new zealand'},
	{cat:'sustainability', locale:'india'},
	{cat:'sustainability', locale:'malaysia'},
	{cat:'sustainability', locale:'philippines'},
	{cat:'sustainability', locale:'indonesia'}]},
{id:"48", empName:"Susan Maclennan", empTitle:"Director", empDepartment:"Retail", telNo:"+852 2840 4891", email:"smaclennan@savills.com.hk", location:"Hong Kong", experience:"17", languages:"English & Cantonese", expertise:"Retail Leasing / Shopping Centres/ Retail Consultancy", workCat:[
	{cat:'retail', locale:'china'},
	{cat:'retail', locale:'hong kong'},
	{cat:'retail', locale:'macau'},
	{cat:'retail', locale:'taiwan'},
	{cat:'retail', locale:'japan'},
	{cat:'retail', locale:'south korea'},
	{cat:'retail', locale:'singapore'},
	{cat:'retail', locale:'thailand'},
	{cat:'retail', locale:'vietnam'},
	{cat:'retail', locale:'myanmar'},
	{cat:'retail', locale:'australia'},
	{cat:'retail', locale:'new zealand'},
	{cat:'retail', locale:'india'},
	{cat:'retail', locale:'malaysia'},
	{cat:'retail', locale:'philippines'},
	{cat:'retail', locale:'indonesia'}]},
{id:"49", empName:"Sulian Tan-Wijaya", empTitle:"Senior Director", empDepartment:"Retail & Lifestyle", telNo:"+65 6836 3880", email:"stwijaya@savills.com.sg", location:"Singapore", experience:"10", languages:"English, Mandarin Chinese & Indonesian", expertise:"Retail, F&B, lifestyle, real estate, banking, legal", workCat:[
	{cat:'retail', locale:'china'},
	{cat:'retail', locale:'hong kong'},
	{cat:'retail', locale:'macau'},
	{cat:'retail', locale:'taiwan'},
	{cat:'retail', locale:'japan'},
	{cat:'retail', locale:'south korea'},
	{cat:'retail', locale:'singapore'},
	{cat:'retail', locale:'thailand'},
	{cat:'retail', locale:'vietnam'},
	{cat:'retail', locale:'myanmar'},
	{cat:'retail', locale:'australia'},
	{cat:'retail', locale:'new zealand'},
	{cat:'retail', locale:'india'},
	{cat:'retail', locale:'malaysia'},
	{cat:'retail', locale:'philippines'},
	{cat:'retail', locale:'indonesia'}]},
{id:"50", empName:"Shirley Huang", empTitle:"Associate Director", empDepartment:"", telNo:"+86755 8828 5345", email:"shirley.huang@Savills.com.cn", location:"Shenzhen", experience:"12", languages:"English, Mandarin, & Cantonese", expertise:"Commercial, Tenant Representation, and Residential", workCat:[
	{cat:'tenant representation', locale:'china'}]},
{id:"53", empName:"Leighton Hunzinker", empTitle:"Director", empDepartment:"Retailer Representation", telNo:"+61 (0) 28215 8838", email:"Lhunziker@savills.com.au", location:"Sydney, Australia", experience:"20", languages:"English", expertise:"Retail leasing, retail management & redevelopment", workCat:[
	{cat:'retail', locale:'china'},
	{cat:'retail', locale:'hong kong'},
	{cat:'retail', locale:'macau'},
	{cat:'retail', locale:'taiwan'},
	{cat:'retail', locale:'japan'},
	{cat:'retail', locale:'south korea'},
	{cat:'retail', locale:'singapore'},
	{cat:'retail', locale:'thailand'},
	{cat:'retail', locale:'vietnam'},
	{cat:'retail', locale:'myanmar'},
	{cat:'retail', locale:'australia'},
	{cat:'retail', locale:'new zealand'},
	{cat:'retail', locale:'india'},
	{cat:'retail', locale:'malaysia'},
	{cat:'retail', locale:'philippines'},
	{cat:'retail', locale:'indonesia'}]},
{id:"54", empName:"Yann Deschamps", empTitle:"Director", empDepartment:"Commercial", telNo:"", email:"", location:"Shanghai, China", experience:"Over 12", languages:"English, Mandarin, French & Spanish", expertise:"Commercial, Tenant Representation & Industrial", workCat:[{cat:'tenant representation', locale:'china'}]},
{id:"56", empName:"Mark Price", empTitle:"Chief Executive Officer", empDepartment:"", telNo:"+66 2636 0300", email:"mprice@savills.co.th", location:"Thailand", experience:"28", languages:"English", expertise:"Office leasing & residential", workCat:[
	{cat:'tenant representation',locale:'thailand'}]},
{id:"57", empName:"Miah Yang", empTitle:"Senior Director", empDepartment:"Retail Services", telNo:"+82 2 2124 4270", email:"mayang@savills.co.kr", location:"Seoul", experience:"", languages:"English & Korean", expertise:"Retail, tenant representation, consultancy", workCat:[
	{cat:'retail', locale:'china'},
	{cat:'retail', locale:'hong kong'},
	{cat:'retail', locale:'macau'},
	{cat:'retail', locale:'taiwan'},
	{cat:'retail', locale:'japan'},
	{cat:'retail', locale:'south korea'},
	{cat:'retail', locale:'singapore'},
	{cat:'retail', locale:'thailand'},
	{cat:'retail', locale:'vietnam'},
	{cat:'retail', locale:'myanmar'},
	{cat:'retail', locale:'australia'},
	{cat:'retail', locale:'new zealand'},
	{cat:'retail', locale:'india'},
	{cat:'retail', locale:'malaysia'},
	{cat:'retail', locale:'philippines'},
	{cat:'retail', locale:'indonesia'}]},
{id:"58", empName:"Siu Wing Chu", empTitle:"Deputy Managing Director", empDepartment:"Savills Shanghai", telNo:"+86 21 6391 6689", email:"swchu@savills-sh.com", location:"Shanghai, China", experience:"16", languages:"English, Mandarin & Cantonese", expertise:"Retail, residential, consultancy projects", workCat:[
	{cat:'retail', locale:'china'},
	{cat:'retail', locale:'hong kong'},
	{cat:'retail', locale:'macau'},
	{cat:'retail', locale:'taiwan'},
	{cat:'retail', locale:'japan'},
	{cat:'retail', locale:'south korea'},
	{cat:'retail', locale:'singapore'},
	{cat:'retail', locale:'thailand'},
	{cat:'retail', locale:'vietnam'},
	{cat:'retail', locale:'myanmar'},
	{cat:'retail', locale:'australia'},
	{cat:'retail', locale:'new zealand'},
	{cat:'retail', locale:'india'},
	{cat:'retail', locale:'malaysia'},
	{cat:'retail', locale:'philippines'},
	{cat:'retail', locale:'indonesia'}]},
{id:"59", empName:"Bryan Kidd", empTitle:"Country Manager, India", empDepartment:"Project Management", telNo:"+91 9535 129604", email:"bkidd@savills.in", location:"Bangalore, India", experience:"5", languages:"English", expertise:"Project Management", workCat:[{cat:'project management lead', locale:'india'}]},
{id:"60", empName:"Robert McGrath", empTitle:"Project Director", empDepartment:"Project Management", telNo:"+852 92893250", email:"RMcGrath@savills.asia", location:"Hong Kong", experience:"25", languages:"English", expertise:"Project Planning & Project Delivery", workCat:[{cat:'project management lead',locale:'philippines'}]},
{id:"61", empName:"Tom Hunt", empTitle:"Project Manager", empDepartment:"Project Management", telNo:"+65 6415 3659", email:"Tom.hunt@savills.com.sg", location:"Singapore", experience:"10", languages:"English", expertise:"Project Management", workCat:[
	{cat:'project management lead', locale:'singapore'},
	{cat:'asia pacific account management', locale:'china'},
	{cat:'asia pacific account management', locale:'hong kong'},
	{cat:'asia pacific account management', locale:'macau'},
	{cat:'asia pacific account management', locale:'taiwan'},
	{cat:'asia pacific account management', locale:'japan'},
	{cat:'asia pacific account management', locale:'south korea'},
	{cat:'asia pacific account management', locale:'singapore'},
	{cat:'asia pacific account management', locale:'thailand'},
	{cat:'asia pacific account management', locale:'vietnam'},
	{cat:'asia pacific account management', locale:'myanmar'},
	{cat:'asia pacific account management', locale:'australia'},
	{cat:'asia pacific account management', locale:'new zealand'},
	{cat:'asia pacific account management', locale:'india'},
	{cat:'asia pacific account management', locale:'malaysia'},
	{cat:'asia pacific account management', locale:'philippines'},
	{cat:'asia pacific account management', locale:'indonesia'}]},
{id:"62", empName:"Richard Emerson", empTitle:"Country Manager", empDepartment:"", telNo:"+95 (0) 9 250 515 035", email:"remerson@savills.com.mm", location:"Myanmar", experience:"Over 20", languages:"English", expertise:"All sectors", workCat:[{cat:'tenant representation',locale:'myanmar'}]},
{id:"63", empName:"James Goh", empTitle:"Investments", empDepartment:"Corporate Real Estate", telNo:"+603 2691 9922 Ext. 257", email:"jamesgoh@savillsrahim-co.com", location:"Kuala Lumpur, Malaysia", experience:"15", languages:"English, Malay", expertise:"Divestment, Tenant Representation", workCat:[{cat:'tenant representation', locale:'malaysia'}]},
{id:"64", empName:"James Mann", empTitle:"Senior Account Manager, Strategic Real Estate Services, Asia Pacific", empDepartment:"", telNo:"+852 2842 4276", email:"jmann@savills.com.hk", location:"Hong Kong", experience:"9", languages:"English", expertise:"Corporate Real Estate", workCat:[
	{cat:'asia pacific account management', locale:'china'},
	{cat:'asia pacific account management', locale:'hong kong'},
	{cat:'asia pacific account management', locale:'macau'},
	{cat:'asia pacific account management', locale:'taiwan'},
	{cat:'asia pacific account management', locale:'japan'},
	{cat:'asia pacific account management', locale:'south korea'},
	{cat:'asia pacific account management', locale:'singapore'},
	{cat:'asia pacific account management', locale:'thailand'},
	{cat:'asia pacific account management', locale:'vietnam'},
	{cat:'asia pacific account management', locale:'myanmar'},
	{cat:'asia pacific account management', locale:'australia'},
	{cat:'asia pacific account management', locale:'new zealand'},
	{cat:'asia pacific account management', locale:'india'},
	{cat:'asia pacific account management', locale:'malaysia'},
	{cat:'asia pacific account management', locale:'philippines'},
	{cat:'asia pacific account management', locale:'indonesia'}]},
{id:"65", empName:"Kai Schindlmayr", empTitle:"Regional Leader, Australia & New Zealand", empDepartment:"", telNo:"+61 (0) 422 002 067", email:"kschindlmayr@savills.com.au", location:"Sydney, Australia", experience:"13", languages:"English", expertise:"Workspace", workCat:[
	{cat:'asia pacific account management',locale:'china'},
	{cat:'asia pacific account management',locale:'hong kong'},
	{cat:'asia pacific account management',locale:'macau'},
	{cat:'asia pacific account management',locale:'taiwan'},
	{cat:'asia pacific account management',locale:'japan'},
	{cat:'asia pacific account management',locale:'south korea'},
	{cat:'asia pacific account management',locale:'singapore'},
	{cat:'asia pacific account management',locale:'thailand'},
	{cat:'asia pacific account management',locale:'vietnam'},
	{cat:'asia pacific account management',locale:'myanmar'},
	{cat:'asia pacific account management',locale:'australia'},
	{cat:'asia pacific account management',locale:'new zealand'},
	{cat:'asia pacific account management',locale:'india'},
	{cat:'asia pacific account management',locale:'malaysia'},
	{cat:'asia pacific account management',locale:'philippines'},
	{cat:'asia pacific account management',locale:'indonesia'},
	{cat:'tenant representation', locale:'new zealand'},
	{cat:'tenant representation', locale:'australia'},
	{cat:'workspace specialist',locale:'china'},
	{cat:'workspace specialist',locale:'hong kong'},
	{cat:'workspace specialist', locale:'macau'},
	{cat:'workspace specialist', locale:'taiwan'},
	{cat:'workspace specialist', locale:'japan'},
	{cat:'workspace specialist', locale:'south korea'},
	{cat:'workspace specialist', locale:'singapore'},
	{cat:'workspace specialist', locale:'thailand'},
	{cat:'workspace specialist', locale:'vietnam'},
	{cat:'workspace specialist', locale:'myanmar'},
	{cat:'workspace specialist', locale:'australia'},
	{cat:'workspace specialist', locale:'new zealand'},
	{cat:'workspace specialist', locale:'india'},
	{cat:'workspace specialist', locale:'malaysia'},
	{cat:'workspace specialist', locale:'philippines'},
	{cat:'workspace specialist', locale:'indonesia'}]},
{id:"66", empName:"Toshio Lin", empTitle:"Director", empDepartment:"", telNo:"+8610 5925 2158", email:"toshio.lin@savills.com.cn", location:"Beijing, China", experience:"Over 25", languages:"English, Chinese (Putonghua & Cantonese), Japanese", expertise:"Asset Management, Facilities Management, Property Management, Project Management, Real Estate Leasing & Procurement & Disposal, EHS, Energy Management, Risk Management, Procurement & etc", workCat:[
	{cat:'intergrated facilities management', locale:'china'},
	{cat:'intergrated facilities management', locale:'hong kong'},
	{cat:'intergrated facilities management', locale:'macau'},
	{cat:'intergrated facilities management', locale:'taiwan'},
	{cat:'intergrated facilities management', locale:'japan'},
	{cat:'intergrated facilities management', locale:'south korea'},
	{cat:'intergrated facilities management', locale:'singapore'},
	{cat:'intergrated facilities management', locale:'thailand'},
	{cat:'intergrated facilities management', locale:'vietnam'},
	{cat:'intergrated facilities management', locale:'myanmar'},
	{cat:'intergrated facilities management', locale:'new zealand'},
	{cat:'intergrated facilities management', locale:'india'},
	{cat:'intergrated facilities management', locale:'malaysia'},
	{cat:'intergrated facilities management', locale:'philippines'},
	{cat:'intergrated facilities management', locale:'indonesia'}]},
{id:"67", empName:"Melissa Ong", empTitle:"Director, Head of Retail", empDepartment:"", telNo:"+86 13001000238", email:"melissa.ong@savills.com.cn", location:"Beijing, China", experience:"Over 10", languages:"English, Mandarin & Cantonese", expertise:"Retail, Tenant Representation & Shopping centers", workCat:[
	{cat:'retail', locale:'china'}]},
{id:"68", empName:"Enid Zhao", empTitle:"Senior Manager", empDepartment:"", telNo:"+8610 5925 2028", email:"enid.zhao@savills.com.cn", location:"Beijing, China", experience:"Over 9", languages:"English, Mandarin", expertise:"Tenant Representation", workCat:[{cat:'tenant representation', locale:'china'}]},
{id:"69", empName:"May Mi", empTitle:"Associate Director", empDepartment:"", telNo:"+8610 592502062", email:"", location:"Beijing, China", experience:"13", languages:"English, Mandarin", expertise:"Tenant Representation", workCat:[{cat:'tenant representation', locale:'china'}]},
{id:"70", empName:"Woody Lam", empTitle:"Managing Director, Savills Southern China", empDepartment:"", telNo:"+86 20 3892 7168", email:"woody.lam@savills.com.cn", location:"Guangzhou, China", experience:"Over 20", languages:"Chinese, English", expertise:"All sectors", workCat:[{cat:'tenant representation', locale:'china'}]},
{id:"71", empName:"Troy Tan", empTitle:"Senior Project Manager", empDepartment:"", telNo:"+86 21 6391 6688", email:"troy.tan@savills.com.cn", location:"Beijing, China", experience:"Over 10", languages:"English, Mandarin", expertise:"Project Management", workCat:[
	{cat:'asia pacific account management',locale:'china'},
	{cat:'asia pacific account management',locale:'hong kong'},
	{cat:'asia pacific account management',locale:'macau'},
	{cat:'asia pacific account management',locale:'taiwan'},
	{cat:'asia pacific account management',locale:'japan'},
	{cat:'asia pacific account management',locale:'south korea'},
	{cat:'asia pacific account management',locale:'singapore'},
	{cat:'asia pacific account management',locale:'thailand'},
	{cat:'asia pacific account management',locale:'vietnam'},
	{cat:'asia pacific account management',locale:'myanmar'},
	{cat:'asia pacific account management',locale:'australia'},
	{cat:'asia pacific account management',locale:'new zealand'},
	{cat:'asia pacific account management',locale:'india'},
	{cat:'asia pacific account management',locale:'malaysia'},
	{cat:'asia pacific account management',locale:'philippines'},
	{cat:'asia pacific account management',locale:'indonesia'},

	{cat:'industrial',locale:'china'},
	{cat:'industrial',locale:'hong kong'},
	{cat:'industrial',locale:'macau'},
	{cat:'industrial',locale:'taiwan'},
	{cat:'industrial',locale:'japan'},
	{cat:'industrial',locale:'south korea'},
	{cat:'industrial',locale:'singapore'},
	{cat:'industrial',locale:'thailand'},
	{cat:'industrial',locale:'vietnam'},
	{cat:'industrial',locale:'myanmar'},
	{cat:'industrial',locale:'australia'},
	{cat:'industrial',locale:'new zealand'},
	{cat:'industrial',locale:'india'},
	{cat:'industrial',locale:'malaysia'},
	{cat:'industrial',locale:'philippines'},
	{cat:'industrial',locale:'indonesia'},

	{cat:'intergrated facilities management',locale:'china'},
	{cat:'intergrated facilities management',locale:'hong kong'},
	{cat:'intergrated facilities management',locale:'macau'},
	{cat:'intergrated facilities management',locale:'taiwan'},
	{cat:'intergrated facilities management',locale:'japan'},
	{cat:'intergrated facilities management',locale:'south korea'},
	{cat:'intergrated facilities management',locale:'singapore'},
	{cat:'intergrated facilities management',locale:'thailand'},
	{cat:'intergrated facilities management',locale:'vietnam'},
	{cat:'intergrated facilities management',locale:'myanmar'},
	{cat:'intergrated facilities management',locale:'australia'},
	{cat:'intergrated facilities management',locale:'new zealand'},
	{cat:'intergrated facilities management',locale:'india'},
	{cat:'intergrated facilities management',locale:'malaysia'},
	{cat:'intergrated facilities management',locale:'philippines'},
	{cat:'intergrated facilities management',locale:'indonesia'},

	{cat:'leadership',locale:'china'},
	{cat:'leadership',locale:'hong kong'},
	{cat:'leadership',locale:'macau'},
	{cat:'leadership',locale:'taiwan'},
	{cat:'leadership',locale:'japan'},
	{cat:'leadership',locale:'south korea'},
	{cat:'leadership',locale:'singapore'},
	{cat:'leadership',locale:'thailand'},
	{cat:'leadership',locale:'vietnam'},
	{cat:'leadership',locale:'myanmar'},
	{cat:'leadership',locale:'australia'},
	{cat:'leadership',locale:'new zealand'},
	{cat:'leadership',locale:'india'},
	{cat:'leadership',locale:'malaysia'},
	{cat:'leadership',locale:'philippines'},
	{cat:'leadership',locale:'indonesia'},

	{cat:'project management lead',locale:'china'},
	{cat:'project management lead',locale:'hong kong'},
	{cat:'project management lead',locale:'macau'},
	{cat:'project management lead',locale:'taiwan'},
	{cat:'project management lead',locale:'japan'},
	{cat:'project management lead',locale:'south korea'},
	{cat:'project management lead',locale:'singapore'},
	{cat:'project management lead',locale:'thailand'},
	{cat:'project management lead',locale:'vietnam'},
	{cat:'project management lead',locale:'myanmar'},
	{cat:'project management lead',locale:'australia'},
	{cat:'project management lead',locale:'new zealand'},
	{cat:'project management lead',locale:'india'},
	{cat:'project management lead',locale:'malaysia'},
	{cat:'project management lead',locale:'philippines'},
	{cat:'project management lead',locale:'indonesia'},

	{cat:'retail',locale:'china'},
	{cat:'retail',locale:'hong kong'},
	{cat:'retail',locale:'macau'},
	{cat:'retail',locale:'taiwan'},
	{cat:'retail',locale:'japan'},
	{cat:'retail',locale:'south korea'},
	{cat:'retail',locale:'singapore'},
	{cat:'retail',locale:'thailand'},
	{cat:'retail',locale:'vietnam'},
	{cat:'retail',locale:'myanmar'},
	{cat:'retail',locale:'australia'},
	{cat:'retail',locale:'new zealand'},
	{cat:'retail',locale:'india'},
	{cat:'retail',locale:'malaysia'},
	{cat:'retail',locale:'philippines'},
	{cat:'retail',locale:'indonesia'},

	{cat:'tenant representation',locale:'china'},
	{cat:'tenant representation',locale:'hong kong'},
	{cat:'tenant representation',locale:'macau'},
	{cat:'tenant representation',locale:'taiwan'},
	{cat:'tenant representation',locale:'japan'},
	{cat:'tenant representation',locale:'south korea'},
	{cat:'tenant representation',locale:'singapore'},
	{cat:'tenant representation',locale:'thailand'},
	{cat:'tenant representation',locale:'vietnam'},
	{cat:'tenant representation',locale:'myanmar'},
	{cat:'tenant representation',locale:'australia'},
	{cat:'tenant representation',locale:'new zealand'},
	{cat:'tenant representation',locale:'india'},
	{cat:'tenant representation',locale:'malaysia'},
	{cat:'tenant representation',locale:'philippines'},
	{cat:'tenant representation',locale:'indonesia'},

	{cat:'sustainability',locale:'china'},
	{cat:'sustainability',locale:'hong kong'},
	{cat:'sustainability',locale:'macau'},
	{cat:'sustainability',locale:'taiwan'},
	{cat:'sustainability',locale:'japan'},
	{cat:'sustainability',locale:'south korea'},
	{cat:'sustainability',locale:'singapore'},
	{cat:'sustainability',locale:'thailand'},
	{cat:'sustainability',locale:'vietnam'},
	{cat:'sustainability',locale:'myanmar'},
	{cat:'sustainability',locale:'australia'},
	{cat:'sustainability',locale:'new zealand'},
	{cat:'sustainability',locale:'india'},
	{cat:'sustainability',locale:'malaysia'},
	{cat:'sustainability',locale:'philippines'},
	{cat:'sustainability',locale:'indonesia'},

	{cat:'workspace specialist',locale:'china'},
	{cat:'workspace specialist',locale:'hong kong'},
	{cat:'workspace specialist',locale:'macau'},
	{cat:'workspace specialist',locale:'taiwan'},
	{cat:'workspace specialist',locale:'japan'},
	{cat:'workspace specialist',locale:'south korea'},
	{cat:'workspace specialist',locale:'singapore'},
	{cat:'workspace specialist',locale:'thailand'},
	{cat:'workspace specialist',locale:'vietnam'},
	{cat:'workspace specialist',locale:'myanmar'},
	{cat:'workspace specialist',locale:'australia'},
	{cat:'workspace specialist',locale:'new zealand'},
	{cat:'workspace specialist',locale:'india'},
	{cat:'workspace specialist',locale:'malaysia'},
	{cat:'workspace specialist',locale:'philippines'},
	{cat:'workspace specialist',locale:'indonesia'}
	]
},
{id:"72", empName:"Peter Adam", empTitle:"Associate Director", empDepartment:"Project Management", telNo:"+65 6415 3871", email:"padam@savills.com.sg", location:"Singapore", experience:"25", languages:"English", expertise:"Property Development & Project Management", workCat:[
	{cat:'asia pacific account management',locale:'china'},
	{cat:'asia pacific account management',locale:'hong kong'},
	{cat:'asia pacific account management',locale:'macau'},
	{cat:'asia pacific account management',locale:'taiwan'},
	{cat:'asia pacific account management',locale:'japan'},
	{cat:'asia pacific account management',locale:'south korea'},
	{cat:'asia pacific account management',locale:'singapore'},
	{cat:'asia pacific account management',locale:'thailand'},
	{cat:'asia pacific account management',locale:'vietnam'},
	{cat:'asia pacific account management',locale:'myanmar'},
	{cat:'asia pacific account management',locale:'australia'},
	{cat:'asia pacific account management',locale:'new zealand'},
	{cat:'asia pacific account management',locale:'india'},
	{cat:'asia pacific account management',locale:'malaysia'},
	{cat:'asia pacific account management',locale:'philippines'},
	{cat:'asia pacific account management',locale:'indonesia'},

	{cat:'industrial',locale:'china'},
	{cat:'industrial',locale:'hong kong'},
	{cat:'industrial',locale:'macau'},
	{cat:'industrial',locale:'taiwan'},
	{cat:'industrial',locale:'japan'},
	{cat:'industrial',locale:'south korea'},
	{cat:'industrial',locale:'singapore'},
	{cat:'industrial',locale:'thailand'},
	{cat:'industrial',locale:'vietnam'},
	{cat:'industrial',locale:'myanmar'},
	{cat:'industrial',locale:'australia'},
	{cat:'industrial',locale:'new zealand'},
	{cat:'industrial',locale:'india'},
	{cat:'industrial',locale:'malaysia'},
	{cat:'industrial',locale:'philippines'},
	{cat:'industrial',locale:'indonesia'},

	{cat:'intergrated facilities management',locale:'china'},
	{cat:'intergrated facilities management',locale:'hong kong'},
	{cat:'intergrated facilities management',locale:'macau'},
	{cat:'intergrated facilities management',locale:'taiwan'},
	{cat:'intergrated facilities management',locale:'japan'},
	{cat:'intergrated facilities management',locale:'south korea'},
	{cat:'intergrated facilities management',locale:'singapore'},
	{cat:'intergrated facilities management',locale:'thailand'},
	{cat:'intergrated facilities management',locale:'vietnam'},
	{cat:'intergrated facilities management',locale:'myanmar'},
	{cat:'intergrated facilities management',locale:'australia'},
	{cat:'intergrated facilities management',locale:'new zealand'},
	{cat:'intergrated facilities management',locale:'india'},
	{cat:'intergrated facilities management',locale:'malaysia'},
	{cat:'intergrated facilities management',locale:'philippines'},
	{cat:'intergrated facilities management',locale:'indonesia'},

	{cat:'leadership',locale:'china'},
	{cat:'leadership',locale:'hong kong'},
	{cat:'leadership',locale:'macau'},
	{cat:'leadership',locale:'taiwan'},
	{cat:'leadership',locale:'japan'},
	{cat:'leadership',locale:'south korea'},
	{cat:'leadership',locale:'singapore'},
	{cat:'leadership',locale:'thailand'},
	{cat:'leadership',locale:'vietnam'},
	{cat:'leadership',locale:'myanmar'},
	{cat:'leadership',locale:'australia'},
	{cat:'leadership',locale:'new zealand'},
	{cat:'leadership',locale:'india'},
	{cat:'leadership',locale:'malaysia'},
	{cat:'leadership',locale:'philippines'},
	{cat:'leadership',locale:'indonesia'},

	{cat:'project management lead',locale:'china'},
	{cat:'project management lead',locale:'hong kong'},
	{cat:'project management lead',locale:'macau'},
	{cat:'project management lead',locale:'taiwan'},
	{cat:'project management lead',locale:'japan'},
	{cat:'project management lead',locale:'south korea'},
	{cat:'project management lead',locale:'singapore'},
	{cat:'project management lead',locale:'thailand'},
	{cat:'project management lead',locale:'vietnam'},
	{cat:'project management lead',locale:'myanmar'},
	{cat:'project management lead',locale:'australia'},
	{cat:'project management lead',locale:'new zealand'},
	{cat:'project management lead',locale:'india'},
	{cat:'project management lead',locale:'malaysia'},
	{cat:'project management lead',locale:'philippines'},
	{cat:'project management lead',locale:'indonesia'},

	{cat:'retail',locale:'china'},
	{cat:'retail',locale:'hong kong'},
	{cat:'retail',locale:'macau'},
	{cat:'retail',locale:'taiwan'},
	{cat:'retail',locale:'japan'},
	{cat:'retail',locale:'south korea'},
	{cat:'retail',locale:'singapore'},
	{cat:'retail',locale:'thailand'},
	{cat:'retail',locale:'vietnam'},
	{cat:'retail',locale:'myanmar'},
	{cat:'retail',locale:'australia'},
	{cat:'retail',locale:'new zealand'},
	{cat:'retail',locale:'india'},
	{cat:'retail',locale:'malaysia'},
	{cat:'retail',locale:'philippines'},
	{cat:'retail',locale:'indonesia'},

	{cat:'tenant representation',locale:'china'},
	{cat:'tenant representation',locale:'hong kong'},
	{cat:'tenant representation',locale:'macau'},
	{cat:'tenant representation',locale:'taiwan'},
	{cat:'tenant representation',locale:'japan'},
	{cat:'tenant representation',locale:'south korea'},
	{cat:'tenant representation',locale:'singapore'},
	{cat:'tenant representation',locale:'thailand'},
	{cat:'tenant representation',locale:'vietnam'},
	{cat:'tenant representation',locale:'myanmar'},
	{cat:'tenant representation',locale:'australia'},
	{cat:'tenant representation',locale:'new zealand'},
	{cat:'tenant representation',locale:'india'},
	{cat:'tenant representation',locale:'malaysia'},
	{cat:'tenant representation',locale:'philippines'},
	{cat:'tenant representation',locale:'indonesia'},

	{cat:'sustainability',locale:'china'},
	{cat:'sustainability',locale:'hong kong'},
	{cat:'sustainability',locale:'macau'},
	{cat:'sustainability',locale:'taiwan'},
	{cat:'sustainability',locale:'japan'},
	{cat:'sustainability',locale:'south korea'},
	{cat:'sustainability',locale:'singapore'},
	{cat:'sustainability',locale:'thailand'},
	{cat:'sustainability',locale:'vietnam'},
	{cat:'sustainability',locale:'myanmar'},
	{cat:'sustainability',locale:'australia'},
	{cat:'sustainability',locale:'new zealand'},
	{cat:'sustainability',locale:'india'},
	{cat:'sustainability',locale:'malaysia'},
	{cat:'sustainability',locale:'philippines'},
	{cat:'sustainability',locale:'indonesia'},

	{cat:'workspace specialist',locale:'china'},
	{cat:'workspace specialist',locale:'hong kong'},
	{cat:'workspace specialist',locale:'macau'},
	{cat:'workspace specialist',locale:'taiwan'},
	{cat:'workspace specialist',locale:'japan'},
	{cat:'workspace specialist',locale:'south korea'},
	{cat:'workspace specialist',locale:'singapore'},
	{cat:'workspace specialist',locale:'thailand'},
	{cat:'workspace specialist',locale:'vietnam'},
	{cat:'workspace specialist',locale:'myanmar'},
	{cat:'workspace specialist',locale:'australia'},
	{cat:'workspace specialist',locale:'new zealand'},
	{cat:'workspace specialist',locale:'india'},
	{cat:'workspace specialist',locale:'malaysia'},
	{cat:'workspace specialist',locale:'philippines'},
	{cat:'workspace specialist',locale:'indonesia'}
	]},
{id:"73", empName:"Christian Mancini", empTitle:"Managing Director", empDepartment:"", telNo:"+81 (0) 3 5562 1717", email:"cmancini@savills.asia", location:"Tokyo, Japan", experience:"15", languages:"English, Japanese", expertise:"Investment sales & asset management", workCat:[
	{cat:'asia pacific account management', locale:'japan'},
	{cat:'industrial', locale:'japan'},
	{cat:'intergrated facilities management', locale:'japan'},
	{cat:'leadership', locale:'japan'},
	{cat:'project management lead', locale:'japan'},
	{cat:'retail', locale:'japan'},
	{cat:'tenant representation', locale:'japan'},
	{cat:'sustainability', locale:'japan'},
	{cat:'workspace specialist', locale:'japan'}
]},
{id:"74", empName:"Rosario Carbonell", empTitle:"Senior Manager", empDepartment:"KMC MAG Group", telNo:"+632 403 5519", email:"rosario@kmcmaggroup.com", location:"Manila, Philippines", experience:"5", languages:"English, Filipino", expertise:"Corporate Real Estate", workCat:[
	{cat:'asia pacific account management', locale:'philippines'},
	{cat:'industrial', locale:'philippines'},
	{cat:'intergrated facilities management', locale:'philippines'},
	{cat:'leadership', locale:'philippines'},
	{cat:'project management lead', locale:'philippines'},
	{cat:'retail', locale:'philippines'},
	{cat:'tenant representation', locale:'philippines'},
	{cat:'sustainability', locale:'philippines'},
	{cat:'workspace specialist', locale:'philippines'}
]}
];

var ourTeamGeneralContent = new Array();

ourTeamGeneralContent = [
{content: '<span class="titleSpan">ACCOUNT EXECUTIVES", empDepartment:"<ul class="yellowList"><li>"Champions" of the Business with Real Estate Experience Exceeding 25 Years</li><li>Responsibilities are in Delivery and Strategy</li></ul></div>'},
{content: '<span class="titleSpan">ACCOUNT MANAGEMENT", empDepartment:"<ul class="yellowList"><li>Support in Managing the Service Delivery</li><li>Ensure Consistent High Quality Delivery</li></ul>'},
{content: '<span class="titleSpan">TRANSACTION MANAGEMENT", empDepartment:"<ul class="yellowList"><li>Provide Guidance and Expertise for Market Appraisals, Acquisitions and Disposals</li><li>Work Closely with the Account Executives and Account Manager to Develop Client Relationships</li></ul>'},
{content: '<span class="titleSpan">PROJECT MANAGEMENT", empDepartment:"<ul class="yellowList"><li>Responsible for Delivery of Building Related Matters at Exit and Occupation of Premises</li><li>Responsibilities are in Delivery and Strategy</li></ul>'},
{content: '<span class="titleSpan">INDUSTRIAL RESEARCH & CONSULTANCY", empDepartment:"<p>Savills has strong centres of excellence for industrial acquisition, disposition and consultancy in Sydney, Singapore and Hong Kong. Our experts service regional requirements for clients from these well located geographical hubs. </p>'},
{content: '<div class="ourTeamGeneralContent" style="height:285px;"><span class="titleSpan">SUSTAINABILITY", empDepartment:"<p class="smallText" style="width: 620px;">Savills Earth was established to assist a broad range of clients to improve their environmental performance in a targeted and practical, yet cost-effective manner. Among other things, our Savills Earth team can:</p><ul class="yellowList"><li>Assist in Developing and Managing Environmental Objectives between Landlords and Tenants</li><li>Advise Tenants on Energy and Water Use Performance Criteria, Fit-out Design and Equipment to Support Environmental Objectives</li><li>Establish &#39;Carbon Footprint&#39; for Organizations and Advise on Mitigation Strategies</li></ul>'},
{content: '<span class="titleSpan">GLOBAL CORPORATE SERVICES", empDepartment:"<p>SavillsCresa provide a full corporate property consultancy service to large commercial occupiers on a global basis. Our team only act for occupiers and always work in our client&#39;s interest to add value to their operation and portfolio.</p>'}
];