var ourTeamArray = new Array();

//Main Sections
ourTeamArray = [
{id:"0", empName:"Brett Ashton", empTitle:"Director", empDepartment:"Global Business Services, North America", telNo:"", email:"bashton@savills.com", location:"United States", experience:"Over 25", languages:"English", expertise:"All Aspects of Commercial", workCat:['all']},
{id:"1", empName:"Fred Placke", empTitle:"Principle", empDepartment:"Corporate Solutions", telNo:"+1 512 716 8262 ", email:"FPlacke@cresa.com", location:"Austin, Texas", experience:"15", languages:"English", expertise:"Corporate clients", workCat:['all','usa corporate solutions']},
{id:"2", empName:"Scott Bumpas", empTitle:"Managing Principle", empDepartment:"Corporate Solutions", telNo:"+1 972 713 4000 ", email:"Scsbumpas@cresa.com", location:"Dallas, Texas", experience:"30", languages:"English", expertise:"Corporate clients", workCat:['all','usa corporate solutions']},
{id:"3", empName:"Mark Jaccom", empTitle:"President and Managing Principle", empDepartment:"Corporate Solutions", telNo:"+1 212 687 4084", email:"mjaccom@cresa.com", location:"New York", experience:"Over 20", languages:"English", expertise:"Tenant representation and corporate clients", workCat:['all','usa corporate solutions']},
{id:"4", empName:"Rich Rhodes", empTitle:"Managing Principle", empDepartment:"Corporate Solutions", telNo:"+1 202 628 0300", email:"rrhodes@cresa.com", location:"Washington, DC", experience:"30", languages:"English", expertise:"Tenant representation and corporate clients", workCat:['all','usa corporate solutions']},
{id:"5", empName:"Matthew Miller", empTitle:"Managing Principle", empDepartment:"Corporate Solutions", telNo:"+1 310 943 5100", email:"mmiller@cresa.com", location:"Los Angeles", experience:"Over 25", languages:"English", expertise:"Entertainment and Technology Companies", workCat:['all','usa corporate solutions']},
{id:"6", empName:"Jim Bryd", empTitle:"Managing Principle", empDepartment:"Brokerage", telNo:"+404 257 8866 main", email:"jbryd@cresa.com", location:"Atlanta Georgia", experience:"36", languages:"English", expertise:"Corporate Services", workCat:['all','usa corporate solutions']},
{id:"7", empName:"Brad Metzger", empTitle:"Managing Principle", empDepartment:"Corporate Services", telNo:"+312 376 4100", email:"bmetzger@cresa.com", location:"Chicago IL", experience:"28", languages:"English", expertise:"Tenant Representation, Development", workCat:['all','usa corporate solutions']},
{id:"8", empName:"Pat Murphy", empTitle:"Managing Principle", empDepartment:"Corporate Services", telNo:"949 706 6929", email:"pmurphy@cresa.com", location:"Orange County", experience:"32", languages:"English", expertise:"Office, Industrial and Development", workCat:['all','usa corporate solutions']},
{id:"9", empName:"Jamie Grossman", empTitle:"Managing Principle", empDepartment:"", telNo:"+416 862 2666 x 233", email:"jgrossman@cresa.com", location:"Toronto", experience:"15", languages:"English", expertise:"Negotiations, Transaction Management, Strategic Advisory Services", workCat:['all','usa corporate solutions']},
{id:"10", empName:"Jack Burns", empTitle:"Managing Principle", empDepartment:"Corporate Services", telNo:"+617 758 6010", email:"jburns@cresa.com", location:"Boston, MA", experience:"", languages:"English", expertise:"Transaction Management, Strategic Planning, Development, Project Management", workCat:['all','usa corporate solutions']}
];

var ourTeamGeneralContent = new Array();

ourTeamGeneralContent = [
{content: '<span class="titleSpan">ACCOUNT EXECUTIVES</span><ul class="yellowList"><li>"Champions" of the Business with Real Estate Experience Exceeding 25 Years</li><li>Responsibilities are in Delivery and Strategy</li></ul></div>'},
{content: '<span class="titleSpan">ACCOUNT MANAGEMENT</span><ul class="yellowList"><li>Support in Managing the Service Delivery</li><li>Ensure Consistent High Quality Delivery</li></ul>'},
{content: '<span class="titleSpan">TRANSACTION MANAGEMENT</span><ul class="yellowList"><li>Provide Guidance and Expertise for Market Appraisals, Acquisitions and Disposals</li><li>Work Closely with the Account Executives and Account Manager to Develop Client Relationships</li></ul>'},
{content: '<span class="titleSpan">PROJECT MANAGEMENT</span><ul class="yellowList"><li>Responsible for Delivery of Building Related Matters at Exit and Occupation of Premises</li><li>Responsibilities are in Delivery and Strategy</li></ul>'},
{content: '<span class="titleSpan">INDUSTRIAL RESEARCH & CONSULTANCY</span><p>Savills has strong centres of excellence for industrial acquisition, disposition and consultancy in Sydney, Singapore and Hong Kong. Our experts service regional requirements for clients from these well located geographical hubs. </p>'},
{content: '<div class="ourTeamGeneralContent" style="height:285px;"><span class="titleSpan">SUSTAINABILITY</span><p class="smallText" style="width: 620px;">Savills Earth was established to assist a broad range of clients to improve their environmental performance in a targeted and practical, yet cost-effective manner. Among other things, our Savills Earth team can:</p><ul class="yellowList"><li>Assist in Developing and Managing Environmental Objectives between Landlords and Tenants</li><li>Advise Tenants on Energy and Water Use Performance Criteria, Fit-out Design and Equipment to Support Environmental Objectives</li><li>Establish &#39;Carbon Footprint&#39; for Organizations and Advise on Mitigation Strategies</li></ul>'},
{content: '<span class="titleSpan">GLOBAL CORPORATE SERVICES</span><p>SavillsCresa provide a full corporate property consultancy service to large commercial occupiers on a global basis. Our team only act for occupiers and always work in our client&#39;s interest to add value to their operation and portfolio.</p>'},
];