var ourTeamArray = new Array();

//Main Sections
ourTeamArray = [
{id:"0", empName:"Iain Chapman", empTitle:"Managing Director, Strategic Real Estate Services, Asia Pacific", empDepartment:"Regional Commercial Services", telNo:"+852 2842 4223", email:"ichapman@savills.com.hk", location:"Hong Kong, China", experience:"25", languages:"English", expertise:"Legal / Banking / Accounting", workCat:['all','leadership','asia pacific account management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
/* {id:"1", empName:"SIMON HA", empTitle:"Director", empDepartment:"Commercial", telNo:"+86 (0) 216 391 6688", email:"simon.ha@savills.com.cn", location:"Shanghai", experience:"9", languages:"English, Cantonese, Mandarin", expertise:"Legal & Banking", workCat:['all'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']}, */
{id:"1", empName:"John Mackenzie", empTitle:"Divisional Director", empDepartment:"Corporate Real Estate Services", telNo:"+61 (0) 2 8215 8982", email:"jmackenzie@savills.com.au", location:"Sydney & Melbourne, Australia", experience:"37", languages:"English", expertise:"All Sectors", workCat:['all','tenant representation'],country:['australia','new zealand']},
{id:"2", empName:"Dominic Harding", empTitle:"Senior Account Manager, Strategic Real Estate Services, Asia Pacific", empDepartment:"Account Management", telNo:"+65 6415 1078 (Ext 3078)", email:"dharding@savills.com.sg", location:"Singapore", experience:"4", languages:"English", expertise:"Corporate Real Estate", workCat:['all','asia pacific account management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"3", empName:"James Sherrard", empTitle:"Senior Director", empDepartment:"Head of Project Management for Asia Pacific", telNo:"+852 2840 4720", email:"jsherrard@savills.asia", location:"Hong Kong", experience:"17", languages:"English & French", expertise:"Project Management & Commercial Management", workCat:['all','leadership','asia pacific account management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"4", empName:"Ben Hopkins", empTitle:"Country Manager", empDepartment:"Project Management", telNo:"+65 6415 3657", email:"bhopkins@savills.com.sg", location:"Singapore", experience:"11", languages:"English & Portuguese", expertise:"Banking / Education / Oil & Gas / Legal / Industrial / Media", workCat:['all','project management'],country:['singapore','malaysia']},
{id:"5", empName:"Phill Andrew", empTitle:"Managing Director", empDepartment:"Project Management", telNo:"+61 (0) 2 82158922", email:"PAndrew@savills.com.au", location:"Sydney, Australia", experience:"25", languages:"English", expertise:"Management System & Fit-out", workCat:['all','project representation'],country:['australia','new zealand']},
{id:"6", empName:"Julian Wyatt", empTitle:"Senior Director", empDepartment:"Facilities management", telNo:"+852 2534 1400 ", email:"jwyatt@savills.com.hk", location:"Hong Kong", experience:"Over 20", languages:"English", expertise:"Facilities management", workCat:['all','intergrated facilities management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"7", empName:"Anthony Mcquade", empTitle:"Senior National Director", empDepartment:"", telNo:"+86 (10) 5925 2002", email:"anthony.mcquade@savills.com.cn", location:"Beijing, China", experience:"21", languages:"English, Mandarin", expertise:"All Sectors", workCat:['all','intergrated facilities management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"8", empName:"Peter Wong", empTitle:"Senior Director", empDepartment:"Facilities management ", telNo:"+852 2534 1781", email:"pwong@savills.com.hk", location:"Hong Kong", experience:"36", languages:"Cantonese & English", expertise:"Building Services Engineering", workCat:['all','intergrated facilities management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"9", empName:"James Chow", empTitle:"Director", empDepartment:"Project Consultancy", telNo:"+852 2534 1409", email:"jchow@savills.com.hk", location:"Hong Kong", experience:"Over 20", languages:"English, Cantonese, Mandarin", expertise:"Building Consultancy Projects", workCat:['all','project representation'],country:['hong kong','macau']},
{id:"10", empName:"Chris Marriott", empTitle:"Chief Executive Officer", empDepartment:"South East Asia", telNo:"+65 6415 3888", email:"cjmarriott@savills.com", location:"Singapore", experience:"Over 20", languages:"English", expertise:"All Sectors", workCat:['all','tenant representation'],country:['singapore']},
/* {id:"13", empName:"JON HUTT", empTitle:"Head of Corporate Real Estate Services", empDepartment:"", telNo:"+44 (0) 1223 347 213", email:"jhutt@savills.com", location:"UK", experience:"Over 20", languages:"English", expertise:"All Areas of Commercial Work", workCat:['all','sustainability'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"14", empName:"BRETT ASHTON", empTitle:"Director", empDepartment:"Global Business Services, North America", telNo:"", email:"bashton@savills.com", location:"United States", experience:"Over 25", languages:"English", expertise:"All Aspects of Commercial", workCat:['all'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"15", empName:"MARK ANDREWS", empTitle:"Head of Corporate Real Estate Services (EMEA)", empDepartment:"", telNo:"+44 (0) 207 409 8772", email:"mandrews@savills.com", location:"UK", experience:"18", languages:"English", expertise:"All Areas of Commercial Work", workCat:['all',],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']}, */
/*{id:"11", empName:"Craig Carr", empTitle:"Director", empDepartment:"Commercial", telNo:"+86 (0) 216 391 6702", email:"craig.carr@savills.com.cn", location:"Shanghai, China", experience:"16", languages:"Mandarin & English", expertise:"All Sectors", workCat:['all','transaction management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
/*{id:"12", empName:"Robert Collins", empTitle:"Chief Executive Officer", empDepartment:"", telNo:"+66 (0) 2636 0300", email:"robertc@savills.com.th", location:"Bangkok Thailand", experience:"22", languages:"English", expertise:"Retail", workCat:['all','transaction management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
{id:"13", empName:"Ricky Lau", empTitle:"Senior Director", empDepartment:"Commercial Leasing", telNo:"+852 2842 4501", email:"rklau@savills.com.hk", location:"Hong Kong", experience:"17", languages:"English, Cantonese & Mandarin", expertise:"Tenant & Landlord Representation, Lease Renewal & Restructure", workCat:['all','tenant representation'],country:['hong kong']},
{id:"14", empName:"Sue Lee", empTitle:"Director", empDepartment:"Commercial Leasing Services", telNo:"+82 (2) 2124 4180", email:"slee@savills.com.kr", location:"Seoul, South Korea", experience:"12", languages:"Korean & English", expertise:"Legal / Pharmaceutical / Korean conglomerate", workCat:['all','tenant representation'],country:['south korea']},
{id:"15", empName:"Kevin Murtagh", empTitle:"Senior Manager", empDepartment:"Commercial", telNo:"+65 6415 7334", email:"kevin.murtagh@savills.com.sg", location:"Singapore", experience:"6", languages:"English, German, Indonesian", expertise:"All Sectors", workCat:['all','tenant representation','asia pacific account management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"16", empName:"Jeffrey Wong", empTitle:"Deputy Senior Director", empDepartment:"Commercial Leasing", telNo:"+852 2842 4290", email:"jwong@savills.com.hk", location:"Hong Kong", experience:"10", languages:"English, Cantonese & Mandarin", expertise:"Tenant Representation & Rent Review", workCat:['all','tenant representation'],country:['hong kong']},
{id:"17", empName:"Rupert Provest", empTitle:"Director", empDepartment:"Agency", telNo:"+84 8 3823 9205", email:"rprovest@savills.com.vn", location:"HCM City Vietnam", experience:"16", languages:"English", expertise:"Commercial", workCat:['all','tenant representation','project representation'],country:['vietnam','indonesia']},
{id:"18", empName:"Thanatchamon Wonglokniyom", empTitle:"Associate Director", empDepartment:"", telNo:"+66 (0) 2 636 0300", email:"thanatchamonw@savills.com.th", location:"Bangkok, Thailand", experience:"16", languages:"Thai & English", expertise:"Retail", workCat:['all','tenant representation'],country:['thailand']},
/*{id:"19", empName:"Gary Wen", empTitle:"Director", empDepartment:"Commercial", telNo:"+86 (10) 5925 2064", email:"gary.wen@savills.com.cn", location:"Beijing, China", experience:"11", languages:"Chinese & English", expertise:"IT & Finance", workCat:['all','sustainability'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
{id:"20", empName:"Toshihlde Honoki", empTitle:"Tenant Representation", empDepartment:"", telNo:"+81 (0) 3 5562 1721", email:"thonoki@savills.co.jp", location:"Tokyo, Japan", experience:"Over 10", languages:"English & Japanese", expertise:"Tenant Representation", workCat:['all','tenant representation'],country:['japan']},
/*{id:"21", empName:"Ashok Kumar", empTitle:"Principal & Managing Director", empDepartment:"Cresa", telNo:"+91 22 6504 7598", email:"akumar@cresapartners.com", location:"India", experience:"Over 20", languages:"Hindi & English", expertise:"IT / Telecom / Entertainment / Industrial", workCat:['all',''],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
{id:"22", empName:"Doug Osborne", empTitle:"Managing Director", empDepartment:"", telNo:"+64 (0) 9951 5910", email:"dosborne@savills.co.nz", location:"New Zealand", experience:"40", languages:"English", expertise:"Strategic and Corporate Real Estate Advisory", workCat:['all','tenant representation'],country:['australia','new zealand']},
{id:"23", empName:"Michael Mccullough", empTitle:"Managing Director", empDepartment:"KMC MAG Group", telNo:"+63 2403 5519", email:"michael@kmcmaggroup.com", location:"Manila, Philippines", experience:"5", languages:"English & Filipino", expertise:"Tenant Representation / Customer Services Centres", workCat:['all','tenant representation'],country:['philippines']},
{id:"24", empName:"Ricky Huang", empTitle:"Associate Director", empDepartment:"Investment ", telNo:"+8662 8789 5828", email:"rhuang@savills.com.tw", location:"Taiwan", experience:"9", languages:"English & Mandarin", expertise:"Industrial & Commercial", workCat:['all'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
/* {id:"31", empName:"PIERS NICKHALLS", empTitle:"Director", empDepartment:"Corporate Real Estate Services", telNo:"+44 (0) 207409 8704", email:"pnickalls@savills.com", location:"London, UK", experience:"20", languages:"English", expertise:"Corporate Real Estate", workCat:['all','transaction management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']}, */
/*{id:"25", empName:"Neil Macgregor", empTitle:"Managing Director", telNo:"+84 8 3823 9205", email:"nmacgregor@savills.com.vn", location:"HCM City Vietnam", experience:"16", languages:"English & Vietnamese", expertise:"Valuation & Investment, Insurance", workCat:['all'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
{id:"26", empName:"Tony Chai", empTitle:"Senior Director", empDepartment:"Project Management", telNo:"+82 2 2124 4231", email:"shchai@savills.com.kr", location:"Seoul", experience:"25", languages:"English & Korean", expertise:"Development and Remodeling", workCat:['all','project representation'],country:['south korea']},
{id:"27", empName:"Adam Evennett", empTitle:"Associate Director", empDepartment:"", telNo:"+86 186 2167 2365", email:"adam.evennett@savills.com.cn", location:"Shanghai, China", experience:"10", languages:"English & intermediate Mandarin", expertise:"Building Refurbishment & Interiors for Retail and Commercial Fit Out", workCat:['all','project representation'],country:['china','taiwan','japan']},
/* {id:"29", empName:"ROBERT ANG", empTitle:"Managing Director", empDepartment:"Savills Rahim & Co", telNo:"+60 (0) 3-2691 9922", email:"robertang@savillsrahim-co.com", location:"Kuala Lumpur", experience:"Over 30", languages:"English & Chinese", expertise:"Real Estate Consultancy", workCat:['all'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']}, */
/*{id:"28", empName:"Simon Smith", empTitle:"Senior Director", empDepartment:"Research & Consultancy", telNo:"+852 2842 4573", email:"ssmith@savills.com.hk", location:"Hong Kong", experience:"Over 19", languages:"English", expertise:"Consultancy Services for Residential, Commercial and Mixed Use Projects", workCat:['all'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
{id:"29", empName:"Darren Curry", empTitle:"Divisional Director", empDepartment:"Industrial", telNo:" +61 (0) 29761 1304", email:"dcurry@savills.com.au", location:"Melbourne & Sydney, Australia", experience:"20", languages:"English", expertise:"Pre-lease Co-ordination / Sales and Leasing Projects / Industrial Investment / Project Marketing", workCat:['all','industrial'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"30", empName:"James Siu", empTitle:"Senior Director", empDepartment:"Industrial and Kowloon Investment Sales", telNo:"+852 2378 8638", email:"jsiu@savills.com.hk", location:"Hong Kong", experience:"30", languages:"Putonghua & Cantonese", expertise:"Industrial / Logistics", workCat:['all','industrial'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"31", empName:"Angela Lu", empTitle:"Manager", empDepartment:"Transaction Management", telNo:"+886 2 8789 5828", email:"Alu@savills.com.tw", location:"Taiwan", experience:"8", languages:"English & Chinese", expertise:"Commercial and Corporate Real Estate", workCat:['all','tenant representation'],country:['taiwan']},
{id:"32", empName:"Ben Vickery", empTitle:"Regional Co-ordinator (Korea)", empDepartment:"Transaction Management & Industrial", telNo:"+82 2 2124 4172 ", email:"bvickery@savills.co.kr", location:"Seoul, South Korea", experience:"3", languages:"English", expertise:"Tenant Rep. Legal, Banking & tech", workCat:['all','industrial'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"33", empName:"Dale O'Toole", empTitle:"National Sustainability Manager", empDepartment:"Sustainability", telNo:"+61 (0) 3 8686 8037 ", email:"dotoole@savills.com.au", location:"Australia", experience:"Over 20", languages:"English", expertise:"Sustainability ", workCat:['all','sustainability'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"34", empName:"Alexander Ang", empTitle:"Marketing Executive", empDepartment:"Transaction Management", telNo:"+6010 366 7087", email:"alexang@savillsrahim-co.com", location:"Kuala Lumpur, Malaysia", experience:"2", languages:"English, Mandarin, Cantonese & Malay", expertise:"Relocation, Tenant-Rep", workCat:['all','tenant representation'],country:['malaysia']},
{id:"35", empName:"Daniel Byrne", empTitle:"Development Manager", empDepartment:"Transaction Management", telNo:"+64 (0) 9 951 5913", email:"dbyrne@savills.com.nz", location:"New Zealand", experience:"11", languages:"English", expertise:"Corporate Commercial Real Estate and Investment Sales", workCat:['all','tenant representation'],country:['australia','new zealand']},
{id:"36", empName:"Jerry Yan", empTitle:"Associate Director", empDepartment:"Transaction Management", telNo:"+8610 5925 2288", email:"jerry.yan@savills.com.cn", location:"Beijing, China", experience:"7", languages:"English & Chinese (Mandarin) ", expertise:"Commercial Real Estate. Tier 1 and Tier 2 Chinese cities", workCat:['all','tenant representation','industrial'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"37", empName:"Terence Lau", empTitle:"Director ", empDepartment:"Transaction Management", telNo:"0755  8828 5703", email:"terence.lau@savills.com.cn", location:"Shenzhen, China", experience:"Over 20", languages:"English, Mandarin & Cantonese", expertise:"All areas of commercial real estate", workCat:['all','tenant representation'],country:['china']},
{id:"38", empName:"Nick Bradstreet", empTitle:"Deputy Managing Director & Head of Leasing", empDepartment:"Retail", telNo:"+852 2842 4255", email:"nbradstreet@savills.com.hk", location:"Hong Kong", experience:"27", languages:"English", expertise:"Retail / Shopping Centers. Regional leasing requirements", workCat:['all','retail'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"39", empName:"Lucas Shen", empTitle:"Manager", empDepartment:"Account Management", telNo:"+852 2842 4247", email:"Lshen@savills.com.hk", location:"Hong Kong", experience:"3", languages:"English and Cantonese", expertise:"Commercial Real Estate", workCat:['all','tenant representation'],country:['hong kong']},
{id:"40", empName:"John Kim", empTitle:"Senior Manager", empDepartment:"Industrial", telNo:"+82 2 2124 4257", email:"dokim@savills.co.kr", location:"Seoul, South Korea", experience:"7", languages:"Korean & English", expertise:"Manufacturing/Automotive/Pharmaceutical", workCat:['all','tenant representation'],country:['south korea']},
{id:"41", empName:"Dominic Peters", empTitle:"Director", empDepartment:"Industrial", telNo:"+65 64515 3638", email:"dpeters@savills.com.sg", location:"Singapore", experience:"20", languages:"English", expertise:"Industrial", workCat:['all','industrial'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
/*{id:"42", empName:"Dick Kwok", empTitle:"Senior Director", empDepartment:"Project Management", telNo:"+852 2534 1777", email:"dkwok@savills.com.hk", location:"Hong Kong", experience:"21", languages:"English, Cantonese and Mandarin", expertise:" Property, Facilities and Asset Management", workCat:['all','project representation','intergrated facilities management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
/*{id:"43", empName:"David Nicholas", empTitle:"General Manager NSW", empDepartment:"Project Management", telNo:"+61 2 8913 4813", email:"dnicholas@savills.com.au", location:"Sydney, Australia", experience:"25", languages:"English", expertise:"Project direction, structuring, risk management and commercial negotiations", workCat:['all','project representation'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
{id:"44", empName:"Chris Adam", empTitle:"General Manager", empDepartment:"Project Management - VIC", telNo:"+61 (0) 3 9445 6841", email:"cadam@savills.com.au", location:"Melbourne, Australia", experience:"10", languages:"English", expertise:"Commercial development, refurbishment and fitout, data centres", workCat:['all','project representation'],country:['australia','new zealand']},
{id:"45", empName:"Doris Lam", empTitle:"Account Manager, Business Development Strategic Real Estate Services", empDepartment:"", telNo:"+852 2842 4410", email:"dslam@savills.com.hk", location:"Hong Kong", experience:"8", languages:"English & Cantonese", expertise:"Corporate Real Estate", workCat:['all','asia pacific account management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
/*{id:"46", empName:"Kara Thompson", empTitle:"Senior Project Manager", empDepartment:"Corporate Real Estate Services", telNo:"+44(0) 207 409 8047", email:"kathompson@savills.com", location:"UK", experience:"6", languages:"English", expertise:"Project & Facilities management", workCat:['all','project representation'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
{id:"47", empName:"Nicky Wightman", empTitle:"Business Strategy Consultant", empDepartment:"", telNo:"+44 (0) 1223 347 087", email:"nwightman@savills.com", location:"UK", experience:"6", languages:"English & French", expertise:"Corporate Strategy & Innovation", workCat:['all','sustainability'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"48", empName:"Susan Maclennan", empTitle:"Director", empDepartment:"Retail", telNo:"+852 2840 4891", email:"smaclennan@savills.com.hk", location:"Hong Kong", experience:"17", languages:"English & Cantonese", expertise:"Retail Leasing / Shopping Centres/ Retail Consultancy", workCat:['all','retail'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"49", empName:"Sulian Tan-Wijaya", empTitle:"Senior Director", empDepartment:"Retail & Lifestyle", telNo:"+65 6836 3880", email:"stwijaya@savills.com.sg", location:"Singapore", experience:"10", languages:"English, Mandarin Chinese & Indonesian", expertise:"Retail, F&B, lifestyle, real estate, banking, legal", workCat:['all','retail'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"50", empName:"Shirley Huang", empTitle:"Associate Director", empDepartment:"", telNo:"86755 8828 5345", email:"shirley.huang@Savills.com.cn", location:"Shenzhen", experience:"12", languages:"English, Mandarin, & Cantonese", expertise:"Commercial, Tenant Representation, and Residential", workCat:['all','tenant representation'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
/*{id:"51", empName:"Christian Mancini", empTitle:"Managing Director", empDepartment:"", telNo:"+81 (0) 3 5562 1717", email:"CMancini@savills.asia", location:"Tokyo, Japan", experience:"15", languages:"English & Japanese", expertise:"Investment sales & asset management", workCat:['all'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
/*{id:"52", empName:"Thomas Brown", empTitle:"Head of Retail Management & Leasing", empDepartment:"Asset Management", telNo:"+61 (0) 2 8215 8893", email:"Tbrown@savills.com.au", location:"Sydney, Australia", experience:"14", languages:"English", expertise:"Retail, commercial & industrial ", workCat:['all','retail'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
{id:"53", empName:"Leighton Hunzinker", empTitle:"Director", empDepartment:"Retailer Representation", telNo:"+61 (0) 28215 8838", email:"Lhunziker@savills.com.au", location:"Sydney, Australia", experience:"20", languages:"English", expertise:"Retail leasing, retail management & redevelopment", workCat:['all','retail'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"54", empName:"Yann Deschamps", empTitle:"Director", empDepartment:"Commercial", telNo:"", email:"", location:"Shanghai, China", experience:"Over 12", languages:"English, Mandarin, French & Spanish", expertise:"Commercial, Tenant Representation & Industrial", workCat:['all','tenant representation'],country:['china']},
/*{id:"55", empName:"Jason Valderrama", empTitle:"Associate Director", empDepartment:"Project Management", telNo:"+63922 873 1040", email:"jvalderrama@savills.asia", location:"Manila, Philippines", experience:"7", languages:"English & Filipino", expertise:"Corporate real estate, project development, commercial fit-out", workCat:['all','project management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},*/
{id:"56", empName:"Mark Price", empTitle:"Chief Executive Officer", empDepartment:"", telNo:"+66 2636 0300", email:"mprice@savills.co.th", location:"Thailand", experience:"28", languages:"English", expertise:"Office leasing & residential", workCat:['all','tenant representation','project representation'],country:['thailand']},
{id:"57", empName:"Miah Yang", empTitle:"Senior Director", empDepartment:"Retail Services", telNo:"+82 2 2124 4270", email:"mayang@savills.co.kr", location:"Seoul", experience:"", languages:"English & Korean", expertise:"Retail, tenant representation, consultancy", workCat:['all','retail'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"58", empName:"Siu Wing Chu", empTitle:"Deputy Managing Director", empDepartment:"Savills Shanghai", telNo:"+86 21 6391 6689", email:"swchu@savills-sh.com", location:"Shanghai, China", experience:"16", languages:"English, Mandarin & Cantonese", expertise:"Retail, residential, consultancy projects", workCat:['all','retail'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"59", empName:"Bryan Kidd", empTitle:"Country Manager - India", empDepartment:"Project Management", telNo:"+91 80 7100 0001", email:"bkidd@savills.in", location:"Pune, India", experience:"5", languages:"English", expertise:"Project Management", workCat:['all','project representation'],country:['india']},
{id:"60", empName:"Robert McGrath", empTitle:"Project Director", empDepartment:"Project Management", telNo:"+852 92893250", email:"RMcGrath@savills.asia", location:"Hong Kong", experience:"25", languages:"English", expertise:"Project Planning & Project Delivery", workCat:['all','project representation'],country:['philippines']},
{id:"61", empName:"Tom Hunt", empTitle:"Project Manager", empDepartment:"Project Management", telNo:"+65 6415 3659", email:"Tom.hunt@savills.com.sg", location:"Singapore", experience:"10", languages:"English", expertise:"Project Management", workCat:['all','project representation','asia pacific account management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"62", empName:"Richard Emerson", empTitle:"Country Manager", empDepartment:"", telNo:"+95 (0) 9 250 515 035", email:"remerson@savills.com.mm", location:"Myanmar", experience:"Over 20", languages:"English", expertise:"All sectors", workCat:['all','tenant representation'],country:['myanmar']},
{id:"63", empName:"James Goh", empTitle:"Investments", empDepartment:"Corporate Real Estate", telNo:"+603 2691 9922 Ext. 257", email:"jamesgoh@savillsrahim-co.com", location:"Kuala Lumpur, Malaysia", experience:"15", languages:"English, Malay", expertise:"Divestment, Tenant Representation", workCat:['all','tenant representation'],country:['malaysia']},
{id:"64", empName:"James Mann", empTitle:"Senior Account Manager, Strategic Real Estate Services, Asia Pacfic", empDepartment:"", telNo:"+852 2842 4276", email:"jmann@savills.com.hk", location:"Hong Kong", experience:"9", languages:"English", expertise:"Corporate Real Estate", workCat:['all','asia pacific account management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"65", empName:"Kai Schindlmayr", empTitle:"Regional Leader, Australia & New Zealand", empDepartment:"", telNo:"+61 (0) 422 002 067", email:"kschindlmayr@savills.com.au", location:"Sydney, Australia", experience:"13", languages:"English", expertise:"Workspace", workCat:['all','asia pacific account management','tenant representation','workspace specialist'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"66", empName:"Toshio Lin", empTitle:"Director", empDepartment:"", telNo:"+8610 5925 2158", email:"toshio.lin@savills.com.cn", location:"Beijing, China", experience:"Over 25", languages:"English, Chinese (Putonghua & Cantonese), Japanese", expertise:"Asset Management, Facilities Management, Property Management, Project Management, Real Estate Leasing & Procurement & Disposal, EHS, Energy Management, Risk Management, Procurement & etc", workCat:['all','project representation','intergrated facilities management'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"67", empName:"Melissa Ong", empTitle:"Director, Head of Retail", empDepartment:"", telNo:"+86 13001000238", email:"melissa.ong@savills.com.cn", location:"Beijing, China", experience:"Over 10", languages:"English, Mandarin & Cantonese", expertise:"Retail, Tenant Representation & Shopping centers", workCat:['all'],country:['china','hong kong','macau','taiwan','japan','south korea','singapore','thailand','vietnam','myanmar','australia','new zealand','india','malaysia','philippines','indonesia']},
{id:"68", empName:"Enid Zhao", empTitle:"Senior Manager", empDepartment:"", telNo:"+86 10 5925 2028", email:"enid.zhao@savills.com.cn", location:"Beijing, China", experience:"Over 9", languages:"English, Mandarin", expertise:"Tenant Representation", workCat:['all','tenant representation'],country:['china']},
{id:"69", empName:"May Mi", empTitle:"Associate Director", empDepartment:"", telNo:"+8610 592502062", email:"", location:"Beijing, China", experience:"13", languages:"English, Mandarin", expertise:"Tenant Representation", workCat:['all','tenant representation'] ,country:['china']},
{id:"70", empName:"Woody Lam", empTitle:"Managing Director, Savills Southern China", empDepartment:"", telNo:"+86 20 3892 7168", email:"woody.lam@savills.com.cn", location:"Guangzhou, China", experience:"Over 20", languages:"Chinese, English", expertise:"All sectors", workCat:['all','tenant representation'] ,country:['china']}
];

var ourTeamGeneralContent = new Array();

ourTeamGeneralContent = [
{content: '<span class="titleSpan">ACCOUNT EXECUTIVES", empDepartment:"<ul class="yellowList"><li>"Champions" of the Business with Real Estate Experience Exceeding 25 Years</li><li>Responsibilities are in Delivery and Strategy</li></ul></div>'},
{content: '<span class="titleSpan">ACCOUNT MANAGEMENT", empDepartment:"<ul class="yellowList"><li>Support in Managing the Service Delivery</li><li>Ensure Consistent High Quality Delivery</li></ul>'},
{content: '<span class="titleSpan">TRANSACTION MANAGEMENT", empDepartment:"<ul class="yellowList"><li>Provide Guidance and Expertise for Market Appraisals, Acquisitions and Disposals</li><li>Work Closely with the Account Executives and Account Manager to Develop Client Relationships</li></ul>'},
{content: '<span class="titleSpan">PROJECT MANAGEMENT", empDepartment:"<ul class="yellowList"><li>Responsible for Delivery of Building Related Matters at Exit and Occupation of Premises</li><li>Responsibilities are in Delivery and Strategy</li></ul>'},
{content: '<span class="titleSpan">INDUSTRIAL RESEARCH & CONSULTANCY", empDepartment:"<p>Savills has strong centres of excellence for industrial acquisition, disposition and consultancy in Sydney, Singapore and Hong Kong. Our experts service regional requirements for clients from these well located geographical hubs. </p>'},
{content: '<div class="ourTeamGeneralContent" style="height:285px;"><span class="titleSpan">SUSTAINABILITY", empDepartment:"<p class="smallText" style="width: 620px;">Savills Earth was established to assist a broad range of clients to improve their environmental performance in a targeted and practical, yet cost-effective manner. Among other things, our Savills Earth team can:</p><ul class="yellowList"><li>Assist in Developing and Managing Environmental Objectives between Landlords and Tenants</li><li>Advise Tenants on Energy and Water Use Performance Criteria, Fit-out Design and Equipment to Support Environmental Objectives</li><li>Establish &#39;Carbon Footprint&#39; for Organizations and Advise on Mitigation Strategies</li></ul>'},
{content: '<span class="titleSpan">GLOBAL CORPORATE SERVICES", empDepartment:"<p>SavillsCresa provide a full corporate property consultancy service to large commercial occupiers on a global basis. Our team only act for occupiers and always work in our client&#39;s interest to add value to their operation and portfolio.</p>'}
];