// JavaScript Document

/*last page id is 242----------------------------*/

var breadcumbArray = new Array();

breadcumbArray = [

/*Who we are section starts*/
{id:'page-id-1', pageName:'Who We Are', levelName:[], levelLinks:[]},
	{id:'page-id-2', pageName:'History', levelName:['Who We Are'], levelLinks:['who-we-are/index.html']},
	{id:'page-id-3', pageName:'Our Partners', levelName:['Who We Are'], levelLinks:['who-we-are/index.html']},
	{id:'page-id-4', pageName:'Our Team - APAC', levelName:['Who We Are'], levelLinks:['who-we-are/index.html']},
	{id:'page-id-5', pageName:'Our Team - Americas', levelName:['Who We Are'], levelLinks:['who-we-are/index.html']},
	{id:'page-id-6', pageName:'Our Team - Europe', levelName:['Who We Are'], levelLinks:['who-we-are/index.html']},
	{id:'page-id-7', pageName:'Number of Offices', levelName:['Who We Are','Savills by Numbers'], levelLinks:['who-we-are/index.html', 'who-we-are/savills-by-numbers/number-of-offices.html']},
	{id:'page-id-11', pageName:'Number of Employees', levelName:['Who We Are','Savills by Numbers'], levelLinks:['who-we-are/index.html', 'who-we-are/savills-by-numbers/number-of-offices.html']},
	{id:'page-id-8', pageName:'Property Managed', levelName:['Who We Are','Savills by Numbers'], levelLinks:['who-we-are/index.html', 'who-we-are/savills-by-numbers/number-of-offices.html']},
	{id:'page-id-10', pageName:'Property and Facilities Management APAC', levelName:['Who We Are','Savills by Numbers'], levelLinks:['who-we-are/index.html', 'who-we-are/savills-by-numbers/number-of-offices.html']},
	{id:'page-id-236', pageName:'Project Management', levelName:['Who We Are','Savills by Numbers'], levelLinks:['who-we-are/index.html', 'who-we-are/savills-by-numbers/number-of-offices.html']},
	{id:'page-id-237', pageName:'Leasing APAC', levelName:['Who We Are','Savills by Numbers'], levelLinks:['who-we-are/index.html', 'who-we-are/savills-by-numbers/number-of-offices.html']},
	{id:'page-id-238', pageName:'Savills Revenue Stream', levelName:['Who We Are','Savills by Numbers'], levelLinks:['who-we-are/index.html', 'who-we-are/savills-by-numbers/number-of-offices.html']},
/*Who we are section ends*/

/*Where We Play section starts*/
{id:'page-id-18', pageName:'Expertise', levelName:[], levelLinks:[]},
	{id:'page-id-19', pageName:'Global Footprint', levelName:['Expertise'], levelLinks:['where-we-play/index.html']},
	{id:'page-id-20', pageName:'APAC Footprint', levelName:['Expertise'], levelLinks:['where-we-play/index.html']},
		{id:'page-id-21', pageName:'Beijing', levelName:['Expertise', 'APAC Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html']},
		{id:'page-id-22', pageName:'Hong Kong', levelName:['Expertise', 'APAC Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html']},
			{id:'page-id-239', pageName:'Clustering', levelName:['Expertise', 'APAC Footprint', 'India'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html', 'where-we-play/apac-footprint-city-guide/india/clustering.html']},
			{id:'page-id-240', pageName:'Transaction Management', levelName:['Expertise', 'APAC Footprint', 'India'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html', 'where-we-play/apac-footprint-city-guide/india/clustering.html']},
			{id:'page-id-241', pageName:'Project Management', levelName:['Expertise', 'APAC Footprint', 'India'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html', 'where-we-play/apac-footprint-city-guide/india/clustering.html']},
			{id:'page-id-242', pageName:'Leadership', levelName:['Expertise', 'APAC Footprint', 'India'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html', 'where-we-play/apac-footprint-city-guide/india/clustering.html']},
		{id:'page-id-23', pageName:'Manila', levelName:['Expertise', 'APAC Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html']},
		{id:'page-id-24', pageName:'Melbourne', levelName:['Expertise', 'APAC Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html']},
		{id:'page-id-25', pageName:'Seoul', levelName:['Expertise', 'APAC Footprint', 'APAC Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html']},
		{id:'page-id-26', pageName:'Central Business District', levelName:['Expertise', 'APAC Footprint','Seoul'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html','where-we-play/apac-footprint-city-guide/seoul/index.html']},
		{id:'page-id-27', pageName:'Gangnam Business District', levelName:['Expertise', 'APAC Footprint','Seoul'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html','where-we-play/apac-footprint-city-guide/seoul/index.html']},
		{id:'page-id-28', pageName:'Yeouido Business District', levelName:['Expertise', 'APAC Footprint','Seoul'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html','where-we-play/apac-footprint-city-guide/seoul/index.html']},
		{id:'page-id-29', pageName:'Shanghai', levelName:['Expertise', 'APAC Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html']},
		{id:'page-id-30', pageName:'Singapore', levelName:['Expertise', 'APAC Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html']},
		{id:'page-id-31', pageName:'Sydney', levelName:['Expertise', 'APAC Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html']},
		{id:'page-id-32', pageName:'Tokyo', levelName:['Expertise', 'APAC Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/apac-footprint.html']},
	{id:'page-id-33', pageName:'Americas Footprint', levelName:['Expertise'], levelLinks:['where-we-play/index.html']},
		{id:'page-id-34', pageName:'Atlanta', levelName:['Expertise', 'Americas Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/america-footprint.html']},
		{id:'page-id-35', pageName:'Boston', levelName:['Expertise', 'Americas Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/america-footprint.html']},
		{id:'page-id-36', pageName:'Chicago', levelName:['Expertise', 'Americas Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/america-footprint.html']},
		{id:'page-id-37', pageName:'Los Angeles', levelName:['Expertise', 'Americas Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/america-footprint.html']},
		{id:'page-id-38', pageName:'New York', levelName:['Expertise', 'Americas Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/america-footprint.html']},
		{id:'page-id-39', pageName:'Orange County', levelName:['Expertise', 'Americas Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/america-footprint.html']},
		{id:'page-id-40', pageName:'Toronto', levelName:['Expertise', 'Americas Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/america-footprint.html']},
		{id:'page-id-41', pageName:'Washington, DC', levelName:['Expertise', 'Americas Footprint'], levelLinks:['where-we-play/index.html', 'where-we-play/america-footprint.html']},	
	{id:'page-id-42', pageName:'Europe Footprint', levelName:['Expertise'], levelLinks:['where-we-play/index.html']},
		{id:'page-id-43', pageName:'Amsterdam', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},
		{id:'page-id-44', pageName:'Dublin', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},
		{id:'page-id-45a', pageName:'Frankfurt - CBD', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},
		{id:'page-id-45b', pageName:'Frankfurt - Mertonviertel', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},
		{id:'page-id-45c', pageName:'Frankfurt - Eschborn', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},
		{id:'page-id-46', pageName:'London', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},
		{id:'page-id-47', pageName:'Madrid', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},
		/*{id:'page-id-48', pageName:'Milan', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},*/
		{id:'page-id-49', pageName:'Paris', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},
		{id:'page-id-50', pageName:'Warsaw', levelName:['Expertise', 'Europe Footprint'], levelLinks:['where-we-play/index.html','where-we-play/europe-footprint.html']},
/*Where We Play section ends*/

/*Our Services section starts*/
{id:'page-id-51', pageName:'Our Services', levelName:[], levelLinks:[]},
	{id:'page-id-52', pageName:'Transaction Management', levelName:['Our Services'], levelLinks:['our-services/index.html']},
		{id:'page-id-53', pageName:'Tiers of Service 1', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
		{id:'page-id-54', pageName:'Tiers of Service 2', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
		{id:'page-id-55', pageName:'Tiers of Service 3', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
		{id:'page-id-56', pageName:'Workbook - Introduction', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-57', pageName:'Workbook - Consultancy', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-58', pageName:'Workbook - Needs Analysis', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-59', pageName:'Workbook - Scope of Work', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-60', pageName:'Workbook - Competitor Comparison', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-61', pageName:'Workbook - Space Utilisation & Standards', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-62', pageName:'Workbook - Budget Appraisal', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-63', pageName:'Workbook - Qualitative Analysis', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-64', pageName:'Workbook - RFP Comparison', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-65', pageName:'Workbook - Negotiation Tracker', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-66', pageName:'Workbook - Quantitative Analysis', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
			{id:'page-id-67', pageName:'Workbook - Cash Flow', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
		{id:'page-id-68', pageName:'Tools', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
		{id:'page-id-69', pageName:'Leadership', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
		{id:'page-id-70', pageName:'Case Studies - Medtronic', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
		{id:'page-id-71', pageName:'Case Studies - Johnsons Controls', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
		{id:'page-id-72', pageName:'Case Studies - Goldman Sachs', levelName:['Our Services','Transaction Management'], levelLinks:['our-services/index.html','our-services/transaction-management-os/index.html']},
	{id:'page-id-73', pageName:'Project Management', levelName:['Our Services'], levelLinks:['our-services/index.html']},
		{id:'page-id-75', pageName:'Tools - Project Management office (PMO)', levelName:['Our Services','Project Management'], levelLinks:['our-services/index.html', 'our-services/project-management-os/index.html']},
		{id:'page-id-76', pageName:'Tools - Aconex', levelName:['Our Services','Project Management'], levelLinks:['our-services/index.html', 'our-services/project-management-os/index.html']},
		{id:'page-id-77', pageName:'Tools - Management Systems', levelName:['Our Services','Project Management'], levelLinks:['our-services/index.html', 'our-services/project-management-os/index.html']},
		{id:'page-id-78', pageName:'Tools - Impact', levelName:['Our Services','Project Management'], levelLinks:['our-services/index.html', 'our-services/project-management-os/index.html']},
		{id:'page-id-79', pageName:'Leadership', levelName:['Our Services','Project Management'], levelLinks:['our-services/index.html', 'our-services/project-management-os/index.html']},
		{id:'page-id-80', pageName:'Case Studies - The Venetian, Macau', levelName:['Our Services','Project Management'], levelLinks:['our-services/index.html', 'our-services/project-management-os/index.html']},
		{id:'page-id-81', pageName:'Case Studies - Sydney Opera House', levelName:['Our Services','Project Management'], levelLinks:['our-services/index.html', 'our-services/project-management-os/index.html']},
		{id:'page-id-82', pageName:'Case Studies - Philips Electronics', levelName:['Our Services','Project Management'], levelLinks:['our-services/index.html', 'our-services/project-management-os/index.html']},
	{id:'page-id-83', pageName:'Facilities Management', levelName:['Our Services'], levelLinks:['our-services/index.html']},
		{id:'page-id-85', pageName:'Workflow', levelName:['Our Services','Facilities Management'], levelLinks:['our-services/index.html', 'our-services/facilities-management-os/index.html']},
		{id:'page-id-86', pageName:'Tools', levelName:['Our Services','Facilities Management'], levelLinks:['our-services/index.html', 'our-services/facilities-management-os/index.html']},
		{id:'page-id-87', pageName:'Leadership', levelName:['Our Services','Facilities Management'], levelLinks:['our-services/index.html', 'our-services/facilities-management-os/index.html']},
		{id:'page-id-88', pageName:'Case Studies - Government Property Agency HK Contract II', levelName:['Our Services','Facilities Management'], levelLinks:['our-services/index.html', 'our-services/facilities-management-os/index.html']},
		{id:'page-id-89', pageName:'Case Studies - Lippo Centre', levelName:['Our Services','Facilities Management'], levelLinks:['our-services/index.html', 'our-services/facilities-management-os/index.html']},
	{id:'page-id-90', pageName:'Global Corporate Relocations', levelName:['Our Services'], levelLinks:['our-services/index.html']},
		{id:'page-id-92', pageName:'People and Places', levelName:['Our Services','Global Corporate Relocations'], levelLinks:['our-services/index.html','our-services/global-corporate-relocations/index.html']},
		{id:'page-id-93', pageName:'Consultation', levelName:['Our Services','Global Corporate Relocations'], levelLinks:['our-services/index.html','our-services/global-corporate-relocations/index.html']},
		{id:'page-id-94', pageName:'Commercial Relocations', levelName:['Our Services','Global Corporate Relocations'], levelLinks:['our-services/index.html','our-services/global-corporate-relocations/index.html']},
		{id:'page-id-95', pageName:'Residental Relocations', levelName:['Our Services','Global Corporate Relocations'], levelLinks:['our-services/index.html','our-services/global-corporate-relocations/index.html']},
/*Our Services section ends*/

/*Our Research section starts*/
{id:'page-id-210', pageName:'Our Research', levelName:[], levelLinks:[]},
{id:'page-id-96', pageName:'City Briefings', levelName:['Our Research'], levelLinks:['our-research/index.html']},
	{id:'page-id-97', pageName:'Beijing', levelName:['Our Research', 'City Briefings', 'APAC'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/apac/beijing-briefing.html']},
		{id:'page-id-98', pageName:'Hong Kong', levelName:['Our Research', 'City Briefings', 'APAC'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/apac/beijing-briefing.html']},
		{id:'page-id-99', pageName:'Manila', levelName:['Our Research', 'City Briefings', 'APAC'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/apac/beijing-briefing.html']},
		{id:'page-id-100', pageName:'Melbourne', levelName:['Our Research', 'City Briefings', 'APAC'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/apac/beijing-briefing.html']},
		{id:'page-id-101', pageName:'Seoul', levelName:['Our Research', 'City Briefings', 'APAC'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/apac/beijing-briefing.html']},
		{id:'page-id-102', pageName:'Shanghai', levelName:['Our Research', 'City Briefings', 'APAC'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/apac/beijing-briefing.html']},
		{id:'page-id-103', pageName:'Singapore', levelName:['Our Research', 'City Briefings', 'APAC'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/apac/beijing-briefing.html']},
		{id:'page-id-104', pageName:'Sydney', levelName:['Our Research', 'City Briefings', 'APAC'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/apac/beijing-briefing.html']},
		{id:'page-id-105', pageName:'Tokyo', levelName:['Our Research', 'City Briefings', 'APAC'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/apac/beijing-briefing.html']},
	{id:'page-id-106', pageName:'Atlanta', levelName:['Our Research', 'City Briefings', 'Americas'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/americas/atlanta-briefing.html']},
		{id:'page-id-107', pageName:'Boston', levelName:['Our Research', 'City Briefings', 'Americas'], levelLinks:['our-research/', 'our-research/city-briefings/index.html','our-research/city-briefings/americas/atlanta-briefing.html']},
		{id:'page-id-108', pageName:'Chicago', levelName:['Our Research', 'City Briefings', 'Americas'], levelLinks:['our-research/', 'our-research/city-briefings/index.html','our-research/city-briefings/americas/atlanta-briefing.html']},
		{id:'page-id-109', pageName:'Los Angeles', levelName:['Our Research', 'City Briefings', 'Americas'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/americas/atlanta-briefing.html']},
		{id:'page-id-110', pageName:'New York', levelName:['Our Research', 'City Briefings', 'Americas'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/americas/atlanta-briefing.html']},
		{id:'page-id-111', pageName:'Orange County', levelName:['Our Research', 'City Briefings', 'Americas'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/americas/atlanta-briefing.html']},
		{id:'page-id-112', pageName:'Toronto', levelName:['Our Research', 'City Briefings', 'Americas'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/americas/atlanta-briefing.html']},
		{id:'page-id-113', pageName:'Washington, DC', levelName:['Our Research', 'City Briefings', 'Americas'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/americas/atlanta-briefing.html']},
	{id:'page-id-114', pageName:'Amsterdam', levelName:['Our Research', 'City Briefings', 'Europe'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/europe/amsterdam-briefing.html']},
		{id:'page-id-115', pageName:'Dublin', levelName:['Our Research', 'City Briefings', 'Europe'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/europe/amsterdam-briefing.html']},
		{id:'page-id-116', pageName:'Frankfurt', levelName:['Our Research', 'City Briefings', 'Europe'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/europe/amsterdam-briefing.html']},
		{id:'page-id-117', pageName:'London', levelName:['Our Research', 'City Briefings', 'Europe'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/europe/amsterdam-briefing.html']},
		{id:'page-id-118', pageName:'Madrid', levelName:['Our Research', 'City Briefings', 'Europe'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/europe/amsterdam-briefing.html']},
		/*{id:'page-id-119', pageName:'Milan', levelName:['Our Research', 'City Briefings', 'Europe'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/europe/amsterdam-briefing.html']},*/
		{id:'page-id-120', pageName:'Paris', levelName:['Our Research', 'City Briefings', 'Europe'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/europe/amsterdam-briefing.html']},
		{id:'page-id-121', pageName:'Warsaw', levelName:['Our Research', 'City Briefings', 'Europe'], levelLinks:['our-research/index.html', 'our-research/city-briefings/index.html','our-research/city-briefings/europe/amsterdam-briefing.html']},
{id:'page-id-122', pageName:'Research Reports', levelName:['Our Research'], levelLinks:['our-research/city-briefings/index.html']},
	{id:'page-id-123', pageName:'APAC', levelName:['Our Research', 'Research Reports'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html']},
		{id:'page-id-211', pageName:'Philippines Investment and Country Guide', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		{id:'page-id-124', pageName:'Beijing Office', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		{id:'page-id-125', pageName:'Hong Kong Office', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		{id:'page-id-126', pageName:'Seoul Office', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		{id:'page-id-127', pageName:'Shanghai Office 1', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		{id:'page-id-212', pageName:'Shanghai Office 2', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		{id:'page-id-128', pageName:'Singapore Office', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		{id:'page-id-129', pageName:'Sydney CBD Office', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		{id:'page-id-130', pageName:'Tokyo Office', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		/* {id:'page-id-131', pageName:'Legal Research', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']}, */
		{id:'page-id-213', pageName:'Manila Real Estate', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
		{id:'page-id-214', pageName:'Melbourne CBD Office', levelName:['Our Research', 'Research Reports','APAC'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html', 'our-research/research-reports/apac/index.html']},
	{id:'page-id-132', pageName:'Americas', levelName:['Our Research', 'Research Reports'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html']},
		{id:'page-id-215', pageName:'Atlanta', levelName:['Our Research', 'Research Reports','Americas'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/americas/index.html']},
		{id:'page-id-216', pageName:'Boston', levelName:['Our Research', 'Research Reports','Americas'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/americas/index.html']},
		{id:'page-id-217', pageName:'Chicago', levelName:['Our Research', 'Research Reports','Americas'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/americas/index.html']},
		{id:'page-id-133', pageName:'Washington, DC', levelName:['Our Research', 'Research Reports','Americas'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/americas/index.html']},
		{id:'page-id-134', pageName:'Los Angeles', levelName:['Our Research', 'Research Reports','Americas'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/americas/index.html']},
		{id:'page-id-135', pageName:'New York', levelName:['Our Research', 'Research Reports','Americas'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/americas/index.html']},
		{id:'page-id-218', pageName:'Orange County', levelName:['Our Research', 'Research Reports','Americas'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/americas/index.html']},
		{id:'page-id-219', pageName:'Toronto', levelName:['Our Research', 'Research Reports','Americas'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/americas/index.html']},
	{id:'page-id-208', pageName:'Europe', levelName:['Our Research', 'Research Reports'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html']},
		{id:'page-id-220', pageName:'European Offices', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-221', pageName:'France Offices', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-222', pageName:'Germany offices', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-223', pageName:'Netherlands offices', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-224', pageName:'Netherlands property markets', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-225', pageName:'Poland investment', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-226', pageName:'Brussels Offices', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-227', pageName:'Dublin offices', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-228', pageName:'London offices 1', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-229', pageName:'London offices 2', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-230', pageName:'Madrid offices', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
		{id:'page-id-231', pageName:'Warsaw offices', levelName:['Our Research', 'Research Reports','Europe'], levelLinks:['our-research/index.html', 'our-research/research-reports/index.html','our-research/research-reports/europe/index.html']},
/*Our Research section ends*/

{id:'page-id-235', pageName:'Benchmarking', levelName:['Our Research'], levelLinks:['our-research/index.html']},

/*Our Clients section starts*/
{id:'page-id-209', pageName:'Our Clients', levelName:[], levelLinks:[]},
	{id:'page-id-136', pageName:'APAC', levelName:['Our Clients', 'Track Record'], levelLinks:['our-clients/index.html','our-clients/index.html']},
	{id:'page-id-232', pageName:'List view', levelName:['Our Clients', 'Track Record', 'APAC'], levelLinks:['our-clients/index.html','our-clients/track-record/tr-apac/index.html','our-clients/track-record/tr-apac/index.html']},
		{id:'page-id-137', pageName:'Americas', levelName:['Our Clients', 'Track Record'], levelLinks:['our-clients/index.html','our-clients/track-record/tr-americas/index.html']},
		{id:'page-id-233', pageName:'List view', levelName:['Our Clients', 'Track Record', 'Americas'], levelLinks:['our-clients/index.html','our-clients/track-record/tr-americas/index.html','our-clients/track-record/tr-americas/index.html']},
		{id:'page-id-138', pageName:'Europe', levelName:['Our Clients', 'Track Record'], levelLinks:['our-clients/index.html','our-clients/track-record/tr-europe/index.html']},
		{id:'page-id-234', pageName:'List view', levelName:['Our Clients', 'Track Record', 'Europe'], levelLinks:['our-clients/index.html','our-clients/track-record/tr-europe/index.html','our-clients/track-record/tr-europe/index.html']},
	{id:'page-id-139', pageName:'Case Studies', levelName:['Our Clients'], levelLinks:['our-clients/index.html']},
	{id:'page-id-140', pageName:'Beijing - Legal', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-141', pageName:'Beijing - Banking', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-142', pageName:'Beijing - Insurance', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-143', pageName:'Hong Kong - Legal', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-144', pageName:'Hong Kong - Banking', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-145', pageName:'Hong Kong - Insurance', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-146', pageName:'Manila - Insurance', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-147', pageName:'Manila - Others', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-148', pageName:'Melbourne - Others 1', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-149', pageName:'Melbourne - Others 2', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-150', pageName:'Seoul - Banking', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-151', pageName:'Seoul - Others', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-152', pageName:'Shanghai - Banking', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-153', pageName:'Singapore - Legal', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-154', pageName:'Singapore - Insurance', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-206', pageName:'Sydney - Legal', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-207', pageName:'Sydney - Others', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-155', pageName:'Tokyo - Legal', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-156', pageName:'Tokyo - Banking', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
		{id:'page-id-157', pageName:'Tokyo - Insurance', levelName:['Our Clients', 'Case Studies', 'APAC'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/apac/beijing-legal.html']},
	{id:'page-id-158', pageName:'Atlanta - CredAbility', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-159', pageName:'Atlanta - FriendHudak&Harris_LLP', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-160', pageName:'Atlanta - GoddardSchool', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-161', pageName:'Atlanta - UndisclosedClient', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-162', pageName:'Boston - Legal', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-163', pageName:'Boston - Technology', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-164', pageName:'Boston - Others', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-165', pageName:'Chicago - Technology 1', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-166', pageName:'Chicago - Technology 2', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-167', pageName:'Chicago - Others', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-168', pageName:'Los Angeles - Technology', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-169', pageName:'Los Angeles - Retail', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-170', pageName:'Los Angeles - Others 1', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-171', pageName:'Los Angeles - Others 2', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-172', pageName:'New York - Legal', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-173', pageName:'New York - Insurance', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-174', pageName:'Orange County - Technology 1', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-175', pageName:'Orange County - Technology 2', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-176', pageName:'Orange County - Others', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-177', pageName:'Toronto - Technology 1', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-178', pageName:'Toronto - Technology 2', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-179', pageName:'Toronto - Others', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-180', pageName:'Washington - Technology 1', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-181', pageName:'Washington - Technology 2', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
		{id:'page-id-182', pageName:'Washington - Others', levelName:['Our Clients', 'Case Studies', 'Americas'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/americas/atlanta-CredAbility.html']},
	{id:'page-id-183', pageName:'Amsterdam - Technology', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-184', pageName:'Amsterdam - Others 1', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-185', pageName:'Amsterdam - Others 2', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-186', pageName:'Dublin - Technology', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-187', pageName:'Dublin - Others 1', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-188', pageName:'Dublin - Others 2', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-189', pageName:'Franfurt - Legal', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-190', pageName:'Franfurt - Insurance', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-191', pageName:'Franfurt - Technology 1', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-192', pageName:'Franfurt - Technology 2', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-193', pageName:'London - Others', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-194', pageName:'Madrid - Others 1', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-195', pageName:'Madrid - Others 2', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-204', pageName:'Paris - Others 1', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-205', pageName:'Paris - Others 2', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-196', pageName:'Madrid - Others 3', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-197', pageName:'Milan - Technology', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-198', pageName:'Milan - Others 1', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-199', pageName:'Milan - Others 2', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-200', pageName:'Warsaw - Technology 1', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-201', pageName:'Warsaw - Technology 2', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']},
		{id:'page-id-202', pageName:'Warsaw - Others', levelName:['Our Clients', 'Case Studies','Europe'], levelLinks:['our-clients/index.html', 'our-clients/case-studies/index.html', 'our-clients/case-studies/europe/amsterdam-technology.html']}
];