var trackRecordArray = new Array();

//Main Sections
trackRecordArray = [
{id:"0", thumb:"../../../images/trackRecord/eaton.png", largeImg:"../../../images/trackRecord/eaton_lrg.png", location:["dublin"], branch:['<span class="bold">30,000 sqft</span> at Dublin'], industry:"technology", companyName:"Eaton Corporation HQ",caseStudy:["../../case-studies/europe/dublin-technology.html"]},
{id:"1", thumb:"../../../images/trackRecord/ellier.png", largeImg:"../../../images/trackRecord/ellier_lrg.png", location:["dublin"], branch:['<span class="bold">65,000 sqft</span> at Dublin'], industry:"Others", companyName:"Ellier Developments",caseStudy:["../../case-studies/europe/dublin-others.html"]},
{id:"2", thumb:"../../../images/trackRecord/statestreet.png", largeImg:"../../../images/trackRecord/statestreet_lrg.png", location:["dublin"], branch:['<span class="bold">185,000 sqft</span> at Dublin'], industry:"Others", companyName:"EA EState Street HQ",caseStudy:["../../case-studies/europe/dublin-others-state-street.html"]},
{id:"3", thumb:"../../../images/trackRecord/freshfiedls.png", largeImg:"../../../images/trackRecord/freshfiedls_lrg.png", location:["frankfurt"], branch:['<span class="bold">6,458 sqft</span> at Franfurt'], industry:"legal", companyName:"Spinn-Off Freshfields",caseStudy:["../../case-studies/europe/franfurt-legal.html"]},
{id:"4", thumb:"../../../images/trackRecord/signaliduna.png", largeImg:"../../../images/trackRecord/signaliduna_lrg.png", location:["frankfurt"], branch:['<span class="bold">26,909 sqft</span> at Franfurt'], industry:"insurance", companyName:"Signal Iduna Gruppe Versicherungen und Finanzen",caseStudy:["../../case-studies/europe/franfurt-insurance.html"]},
{id:"5", thumb:"../../../images/trackRecord/arrowcentraleurope.png", largeImg:"../../../images/trackRecord/arrowcentraleurope_lrg.png", location:["frankfurt"], branch:['<span class="bold">129,167 sqft</span> at Franfurt'], industry:"technology", companyName:"Arrow Central Europe GmbH",caseStudy:["../../case-studies/europe/franfurt-technology.html"]},
{id:"6", thumb:"../../../images/trackRecord/airliquide.png", largeImg:"../../../images/trackRecord/airliquide_lrg.png", location:["frankfurt"], branch:['<span class="bold">269,098 sqft</span> at Franfurt'], industry:"technology", companyName:"Lurgi GmbH / Air Liquide Engineering & Construction",caseStudy:["../../case-studies/europe/franfurt-technology-lurgi.html"]},
{id:"7", thumb:"../../../images/trackRecord/casinogranmadrid.png", largeImg:"../../../images/trackRecord/casinogranmadrid_lrg.png", location:["madrid"], branch:['<span class="bold">32,292-48,437 sqft</span> at Madrid'], industry:"Others", companyName:"Casino de Juego Gran Madrid",caseStudy:["../../case-studies/europe/madrid-others.html"]},
{id:"8", thumb:"../../../images/trackRecord/nbcuniversal.png", largeImg:"../../../images/trackRecord/nbcuniversal_lrg.png", location:["madrid"], branch:['<span class="bold">30,139 sqft</span> at Madrid'], industry:"Others", companyName:"NBC Universal",caseStudy:["../../case-studies/europe/madrid-others-nbc.html"]},
{id:"9", thumb:"../../../images/trackRecord/inventivhealth.png", largeImg:"../../../images/trackRecord/inventivhealth_lrg.png", location:["madrid"], branch:['<span class="bold">8,611 sqft / 8,073 sqft</span> at Madrid'], industry:"Others", companyName:"Inventiv Health",caseStudy:["../../case-studies/europe/madrid-others-inventiv.html"]},
/* {id:"10", thumb:"../../../images/trackRecord/panasonic.png", largeImg:"../../../images/trackRecord/panasonic_lrg.png", location:["milan"], branch:['<span class="bold">27,986 sqft</span> at Milan, Italy'], industry:"technology", companyName:"Panasonic",caseStudy:["../../case-studies/europe/milan-technology.html"]} */
{id:"10", thumb:"../../../images/trackRecord/kia.png", largeImg:"../../../images/trackRecord/kia_lrg.png", location:["warsaw"], branch:['<span class="bold">26,910 sqft</span> at Warsaw'], industry:"technology", companyName:"KIA Motors",caseStudy:["../../case-studies/europe/warsaw-technology.html"]},
{id:"11", thumb:"../../../images/trackRecord/dolby.png", largeImg:"../../../images/trackRecord/dolby_lrg.png", location:["warsaw"], branch:['<span class="bold">19,375 sqft</span> at Warsaw'], industry:"technology", companyName:"Dolby Laboratories",caseStudy:["../../case-studies/europe/warsaw-technology-dolby.html"]},
{id:"12", thumb:"../../../images/trackRecord/publicisgroupe.png", largeImg:"../../../images/trackRecord/publicisgroupe_lrg.png", location:["warsaw"], branch:['<span class="bold">129,167 sqft</span> at Warsaw'], industry:"technology", companyName:"Publicis Groupe",caseStudy:["../../case-studies/europe/warsaw-others.html"]},
{id:"13", thumb:"../../../images/trackRecord/ams.png", largeImg:"../../../images/trackRecord/ams_lrg.png", location:["amsterdam"], branch:['<span class="bold">21,527 sqft</span> at Amsterdam'], industry:"technology", companyName:"American Medical Systems",caseStudy:["../../case-studies/europe/amsterdam-technology.html"]},
{id:"14", thumb:"../../../images/trackRecord/euroclear.png", largeImg:"../../../images/trackRecord/euroclear_lrg.png", location:["amsterdam"], branch:['<span class="bold">12,917 sqft</span> at Amsterdam'], industry:"Others", companyName:"Euroclear",caseStudy:["../../case-studies/europe/amsterdam-others1.html"]},
{id:"15", thumb:"../../../images/trackRecord/nti.png", largeImg:"../../../images/trackRecord/nti_lrg.png", location:["amsterdam"], branch:['<span class="bold">19,375 sqft</span> at Amsterdam'], industry:"Others", companyName:"NTI Nederlands Talen Inst.",caseStudy:["../../case-studies/europe/amsterdam-others2.html"]}
];