var trackRecordArray = new Array();

//Main Sections
trackRecordArray = [
{id:"0", thumb:"../../../images/trackRecord/eaton.png", largeImg:"../../../images/trackRecord/eaton_lrg.png", location:["dublin"], branch:['<span class="bold">2,787 sq m</span> at Dublin'], industry:"technology", companyName:"Eaton Corporation HQ",caseStudy:["../../case-studies/europe/dublin-technology.html"]},
{id:"1", thumb:"../../../images/trackRecord/ellier.png", largeImg:"../../../images/trackRecord/ellier_lrg.png", location:["dublin"], branch:['<span class="bold">6,039 sq m</span> at Dublin'], industry:"Others", companyName:"Ellier Developments",caseStudy:["../../case-studies/europe/dublin-financial-1.html"]},
{id:"2", thumb:"../../../images/trackRecord/statestreet.png", largeImg:"../../../images/trackRecord/statestreet_lrg.png", location:["dublin"], branch:['<span class="bold">17,187 sq m</span> at Dublin'], industry:"Others", companyName:"EA EState Street HQ",caseStudy:["../../case-studies/europe/dublin-financial-2.html"]},
{id:"3", thumb:"../../../images/trackRecord/freshfiedls.png", largeImg:"../../../images/trackRecord/freshfiedls_lrg.png", location:["frankfurt"], branch:['<span class="bold">600 sq m</span> at Frankfurt'], industry:"legal", companyName:"Freshfields Spin off",caseStudy:["../../case-studies/europe/frankfurt-legal.html"]},
{id:"4", thumb:"../../../images/trackRecord/signaliduna.png", largeImg:"../../../images/trackRecord/signaliduna_lrg.png", location:["frankfurt"], branch:['<span class="bold">2,500 sq m</span> at Frankfurt'], industry:"insurance", companyName:"Signal Iduna Gruppe Versicherungen und Finanzen",caseStudy:["../../case-studies/europe/frankfurt-financial.html"]},
{id:"5", thumb:"../../../images/trackRecord/arrowcentraleurope.png", largeImg:"../../../images/trackRecord/arrowcentraleurope_lrg.png", location:["frankfurt"], branch:['<span class="bold">12,000 sq m</span> at Frankfurt'], industry:"technology", companyName:"Arrow Central Europe GmbH",caseStudy:["../../case-studies/europe/frankfurt-technology.html"]},
{id:"6", thumb:"../../../images/trackRecord/airliquide.png", largeImg:"../../../images/trackRecord/airliquide_lrg.png", location:["frankfurt"], branch:['<span class="bold">25,000 sq m</span> at Frankfurt'], industry:"technology", companyName:"Lurgi GmbH / Air Liquide Engineering & Construction",caseStudy:["../../case-studies/europe/frankfurt-oil-gas.html"]},
{id:"7", thumb:"../../../images/trackRecord/casinogranmadrid.png", largeImg:"../../../images/trackRecord/casinogranmadrid_lrg.png", location:["madrid"], branch:['<span class="bold">3,000–4,500 sq m</span> in Madrid'], industry:"Others", companyName:"Casino de Juego Gran Madrid",caseStudy:["../../case-studies/europe/madrid-leisure.html"]},
{id:"8", thumb:"../../../images/trackRecord/nbcuniversal.png", largeImg:"../../../images/trackRecord/nbcuniversal_lrg.png", location:["madrid"], branch:['<span class="bold">2,800 sq m</span> in Madrid'], industry:"Others", companyName:"NBC Universal",caseStudy:["../../case-studies/europe/madrid-communications.html"]},
{id:"9", thumb:"../../../images/trackRecord/inventivhealth.png", largeImg:"../../../images/trackRecord/inventivhealth_lrg.png", location:["madrid"], branch:['<span class="bold">800 sq m/750 sq m</span> in Madrid'], industry:"Others", companyName:"Inventiv Health",caseStudy:["../../case-studies/europe/madrid-medical.html"]},
/* {id:"10", thumb:"../../../images/trackRecord/panasonic.png", largeImg:"../../../images/trackRecord/panasonic_lrg.png", location:["milan"], branch:['<span class="bold">27,986 sqft</span> at Milan, Italy'], industry:"technology", companyName:"Panasonic",caseStudy:["../../case-studies/europe/milan-technology.html"]} */
{id:"10", thumb:"../../../images/trackRecord/kia.png", largeImg:"../../../images/trackRecord/kia_lrg.png", location:["warsaw"], branch:['<span class="bold">2,500 sq m</span> at Warsaw'], industry:"technology", companyName:"KIA Motors",caseStudy:["../../case-studies/europe/warsaw-automotive.html"]},
{id:"11", thumb:"../../../images/trackRecord/dolby.png", largeImg:"../../../images/trackRecord/dolby_lrg.png", location:["warsaw"], branch:['<span class="bold">1,800 sq m</span> at Warsaw'], industry:"technology", companyName:"Dolby Laboratories",caseStudy:["../../case-studies/europe/warsaw-technology.html"]},
{id:"12", thumb:"../../../images/trackRecord/publicisgroupe.png", largeImg:"../../../images/trackRecord/publicisgroupe_lrg.png", location:["warsaw"], branch:['<span class="bold">12,000 sq m</span> at Warsaw'], industry:"technology", companyName:"Publicis Groupe",caseStudy:["../../case-studies/europe/warsaw-advertising.html"]},
{id:"13", thumb:"../../../images/trackRecord/ams.png", largeImg:"../../../images/trackRecord/ams_lrg.png", location:["amsterdam"], branch:['<span class="bold">2,000 sq m</span> at Amsterdam'], industry:"technology", companyName:"American Medical Systems",caseStudy:["../../case-studies/europe/amsterdam-medical.html"]},
{id:"14", thumb:"../../../images/trackRecord/euroclear.png", largeImg:"../../../images/trackRecord/euroclear_lrg.png", location:["amsterdam"], branch:['<span class="bold">1,200 sq m</span> at Amsterdam'], industry:"Others", companyName:"Euroclear",caseStudy:["../../case-studies/europe/amsterdam-financial.html"]},
{id:"15", thumb:"../../../images/trackRecord/nti.png", largeImg:"../../../images/trackRecord/nti_lrg.png", location:["amsterdam"], branch:['<span class="bold">1,800 sq m</span> at Amsterdam'], industry:"Others", companyName:"NTI Nederlands Talen Inst.",caseStudy:["../../case-studies/europe/amsterdam-education.html"]}
];